class_name SpriteArt
extends RefCounted

## Hand-authored pixel art. Every sprite is a square grid of single characters
## resolved through its own palette, where "." means transparent.
## Run tools/sprite_forge.tscn to bake these into PNG files under OUTPUT_DIRECTORY.

const OUTPUT_DIRECTORY := "res://assets/sprites"

const HERO_PALETTES := {
	"arclight": {"o": "0b1b33", "b": "2b6fd6", "l": "63b3ff", "w": "e8f4ff", "y": "ffe066"},
	"bulwark": {"o": "2a1405", "b": "e0a44b", "l": "ffd08a", "w": "fff2d8", "y": "c3ccda"},
	"warden": {"o": "0d2b1a", "b": "3f9e57", "l": "8fe08f", "w": "eaffe9", "y": "ffe9a8"},
	"frostbinder": {"o": "0a2233", "b": "3aa9e0", "l": "9fe3ff", "w": "ffffff", "y": "d8f7ff"},
}

const HERO_ROWS := {
	"arclight": [
		"................",
		"......oooo....y.",
		".....obbbbo..y..",
		"....obllllbo.yy.",
		"....oblwwlbo..y.",
		"....obl..lbo.y..",
		"...obbbbbbbo....",
		"..obbllllllbbo..",
		"..obblwwwwlbbo..",
		"..obblwwwwlbbo..",
		"..obbllllllbbo..",
		"...obbbbbbbbo...",
		"....ob.oo.bo....",
		"....oo.oo.oo....",
		".....o....o.....",
		"................",
	],
	"bulwark": [
		"................",
		"..o...oooo......",
		"..oo.obbbbo.....",
		"...ooblllbbo....",
		"....oblwwlbo....",
		".yy.obl..lbo....",
		"yyyyobbbbbbo....",
		"yylyobbllllbbo..",
		"yyllobblwwlbbo..",
		"yylyobbllllbbo..",
		"yyyyobbbbbbbo...",
		".yy.obbbbbbo....",
		"....ob.oo.bo....",
		"....oo.oo.oo....",
		".....o....o.....",
		"................",
	],
	"warden": [
		"................",
		"......oooo..ww..",
		".....obbbbo.wlw.",
		"....obllllbo.w..",
		"....oblwwlbo.o..",
		"....obl..lbo.o..",
		"...obbbbbbbo.o..",
		"..obbllllllbbo..",
		"..obblwwwwlbbo..",
		"..obblwwwwlbbo..",
		"..obbllllllbbo..",
		"...obbbbbbbbo...",
		"....ob.oo.bo....",
		"....oo.oo.oo....",
		".....o....o.....",
		"................",
	],
	"frostbinder": [
		"................",
		"......oooo......",
		"..w..obbbbo..w..",
		".wlw.obllllbo.w.",
		"..w.oblwwlbo..w.",
		"....obl..lbo....",
		"...obbbbbbbo....",
		"..obbllllllbbo..",
		"..obblwwwwlbbo..",
		"..obblwwwwlbbo..",
		"..obbllllllbbo..",
		"...obbbbbbbbo...",
		"....ob.oo.bo....",
		"....oo.oo.oo....",
		".....o....o.....",
		"................",
	],
}

const ENEMY_PALETTES := {
	"grunt": {"o": "5a1414", "f": "ff5d5d", "l": "ffb0a9", "e": "2a0a0a", "w": "ffffff"},
	"swarmling": {"o": "6b3a08", "f": "ff9d4d", "l": "ffd9a8", "e": "2a1400", "w": "ffffff"},
	"spitter": {"o": "3d1a63", "f": "b06bff", "l": "e2c4ff", "e": "1a0630", "w": "ffffff"},
	"drifter": {"o": "1d4a63", "f": "8ad7ff", "l": "e6f7ff", "e": "0a2233", "w": "ffffff"},
	"brute": {"o": "3d0a12", "f": "a52f3d", "l": "ff8f7a", "e": "1a0206", "w": "ffe0d0"},
	"stalker": {"o": "6b1a58", "f": "ff4fd0", "l": "ffc4f0", "e": "2a0620", "w": "ffffff"},
	"bomber": {"o": "6b5405", "f": "ffdc4d", "l": "fff3b0", "e": "2a2000", "w": "ff6b3d"},
	"hexer": {"o": "0d4a44", "f": "3fd0c0", "l": "c2fff6", "e": "032420", "w": "ffffff"},
	"sentinel": {"o": "3a4152", "f": "8f9bb3", "l": "dfe6f2", "e": "161a24", "w": "ffd166"},
	"splitter": {"o": "1f5c1f", "f": "6fdc6f", "l": "d6ffd6", "e": "0a2a0a", "w": "ffffff"},
	"charger": {"o": "6b2f05", "f": "ff7a29", "l": "ffd0a8", "e": "2a1000", "w": "ffffff"},
	"summoner": {"o": "4a1a6b", "f": "c85cff", "l": "eccfff", "e": "1c0630", "w": "ffffff"},
	"lurker": {"o": "241809", "f": "5a3d2b", "l": "8a6a4a", "e": "120c04", "w": "ffe066"},
}

const ENEMY_ROWS := {
	"grunt": [
		"................",
		".....oooooo.....",
		"....offffffo....",
		"...offffffffo...",
		"..offffffffffo..",
		"..offeeffeeffo..",
		"..offeeffeeffo..",
		"..offffffffffo..",
		"..offfllllfffo..",
		"..ooffffffffoo..",
		".o.offffffffo.o.",
		".o..offffffo..o.",
		"....o.oooo.o....",
		"....o.o..o.o....",
		"...oo.o..o.oo...",
		"................",
	],
	"swarmling": [
		"................",
		"................",
		"................",
		"......oooo......",
		".....offffo.....",
		"....offffffo....",
		"...offeffeffo...",
		"...offeffeffo...",
		"...offffffffo...",
		"...offllllffo...",
		"....offffffo....",
		"..o..oooooo..o..",
		"..o.o.o..o.o.o..",
		"...oo.o..o.oo...",
		"................",
		"................",
	],
	"spitter": [
		"................",
		"......oooo......",
		".....offffo.....",
		"....offffffo....",
		"...offeffeffo...",
		"...offeffeffo...",
		"..offffffffffo..",
		"..offooooooffo..",
		"..offolllloffo..",
		"..offooooooffo..",
		"..offffffffffo..",
		"...offffffffo...",
		"....oooooooo....",
		"....o.o..o.o....",
		"...oo.o..o.oo...",
		"................",
	],
	"drifter": [
		"................",
		"..o..........o..",
		".ofo.oooooo.ofo.",
		".offoffffffoffo.",
		".offlfffffflffo.",
		"..offfeffefffo..",
		"...offeffeffo...",
		"...offffffffo...",
		"...offllllffo...",
		"....offffffo....",
		".....oooooo.....",
		"......o..o......",
		".....o....o.....",
		"................",
		"................",
		"................",
	],
	"brute": [
		"..o..........o..",
		"..oo........oo..",
		"..ofo.oooo.ofo..",
		"..offooffooffo..",
		"...offffffffo...",
		"..offffffffffo..",
		".offfeeffeefffo.",
		".offfeeffeefffo.",
		".offffffffffffo.",
		".offfwwwwwwfffo.",
		".offfwoooowfffo.",
		".offffffffffffo.",
		"..offffffffffo..",
		"..oo.oooooo.oo..",
		"....oo....oo....",
		"...oo......oo...",
	],
	"stalker": [
		"................",
		"................",
		".......oo.......",
		"......offo......",
		".....offffo.....",
		"....offffffo....",
		"...offeffeffo...",
		"...offffffffo...",
		"..offfllllfffo..",
		"..offffffffffo..",
		".o.offffffffo.o.",
		".oo..oooooo..oo.",
		"..o..o.oo.o..o..",
		"....oo....oo....",
		"................",
		"................",
	],
	"bomber": [
		"................",
		"..........w.....",
		".........w......",
		"..o.....o.......",
		".ofo..oooo..o...",
		".offo.offo.ofo..",
		"..offoffffoffo..",
		"..offffffffffo..",
		"..offeeffeeffo..",
		"..offffffffffo..",
		"..offllllllffo..",
		"...offffffffo...",
		"....oooooooo....",
		"................",
		"................",
		"................",
	],
	"hexer": [
		"................",
		"......oooo......",
		".....offffo.....",
		"....offffffo....",
		"....offeeffo....",
		"....offffffo....",
		"...offffffffo...",
		"..offfllllfffo..",
		".o.offffffffo.o.",
		"olo.offffffo.olo",
		".o..offffffo..o.",
		"....offffffo....",
		"....offllffo....",
		"....oooooooo....",
		".....o....o.....",
		"................",
	],
	"sentinel": [
		"................",
		"....oooooooo....",
		"...offffffffo...",
		"..offwwwwwwffo..",
		"..offffffffffo..",
		".offfeeffeefffo.",
		".offfeeffeefffo.",
		".offffffffffffo.",
		".offoffffffoffo.",
		".offoffffffoffo.",
		".offffffffffffo.",
		"..offffffffffo..",
		"..offoooooofffo.",
		"...oo.o..o.oo...",
		"...o..o..o..o...",
		"................",
	],
	"splitter": [
		"................",
		".....oooooo.....",
		"....offffffo....",
		"...offfoofffo...",
		"..offffoofffffo.",
		"..offeefooeeffo.",
		"..offffoofffffo.",
		"..offffoofffffo.",
		"..offllooollffo.",
		"..offffoofffffo.",
		"...offffoofffo..",
		"....oooooooo....",
		"....o.o..o.o....",
		"...oo.o..o.oo...",
		"................",
		"................",
	],
	"lurker": [
		"................",
		"................",
		"................",
		"......oooo......",
		"....offffffo....",
		"...offewweffo...",
		"..offffffffffo..",
		".offfllllllfffo.",
		".offffffffffffo.",
		".offffffffffffo.",
		"..offffffffffo..",
		"...o.o....o.o...",
		"..oo.o....o.oo..",
		"................",
		"................",
		"................",
	],
	"charger": [
		"................",
		"...oo......oo...",
		"..ofo......ofo..",
		"..offo.oo.offo..",
		"...offoffoffo...",
		"..offffffffffo..",
		".offfeeffeefffo.",
		".offfeeffeefffo.",
		".offffffffffffo.",
		".offfwwwwwwfffo.",
		".offffffffffffo.",
		"..offffffffffo..",
		"...oooooooooo...",
		"...o.o....o.o...",
		"..oo.o....o.oo..",
		"................",
	],
	"summoner": [
		"................",
		"......oooo......",
		".....offffo.....",
		"....offffffo....",
		"....offwwffo....",
		"....offeeffo....",
		"...offffffffo...",
		"..offfffffffffo.",
		"..offfllllfffo..",
		".o.offffffffo.o.",
		"olo.offffffo.olo",
		".o..offffffo..o.",
		"....offffffo....",
		"....oooooooo....",
		".....o....o.....",
		"................",
	],
}

const BOSS_PALETTES := {
	"ravager": {"o": "2b0410", "f": "7a0f2b", "l": "ff6b6b", "e": "ffdc4d", "w": "ffe0d0", "d": "45061a"},
	"stormcaller": {"o": "071b3d", "f": "2f6bff", "l": "b8d4ff", "e": "ffffff", "w": "8ad7ff", "d": "14306b"},
}

const BOSS_ROWS := {
	"ravager": [
		"..o..................o..",
		"..oo................oo..",
		"..ofo..............ofo..",
		"..offo....oooo....offo..",
		"..offfo.oodddoo.offffo..",
		"...offoodddddddooffo....",
		"...offoddddddddoffo.....",
		"..offfddddddddddfffo....",
		".offfddddddddddddfffo...",
		".offddddddddddddddffo...",
		".offddeeeddddeeeddffo...",
		".offddeeeddddeeeddffo...",
		".offddddddddddddddffo...",
		".offdddwwwwwwwwdddffo...",
		".offdddwooooooowdddffo..",
		".offdddwooooooowdddffo..",
		".offdddwwwwwwwwdddffo...",
		".offddddddddddddddffo...",
		"..offddddddddddddffo....",
		"..offfddddddddddfffo....",
		"...ooffddddddddffoo.....",
		"....o.ooolllooo.o.......",
		"......oo.o..o.oo........",
		".....oo...........oo....",
	],
	"stormcaller": [
		"..........oooo..........",
		"........oodddoo.........",
		".......odddddddo........",
		"......oddddddddddo......",
		"..o...odddeeeedddo...o..",
		".owo..oddeeeeeeddo..owo.",
		".owwo.oddddddddddo.owwo.",
		"owwwwoodddddddddddoowwww",
		"owwwwwoddddddddddowwwwwo",
		".owwwoodddddddddoowwwwo.",
		"..owo..offddddffo..owo..",
		"...o...offffffffo...o...",
		".......offffffffo.......",
		"......offfllllfffo......",
		"......offfllllfffo......",
		".......offffffffo.......",
		"........offffffo........",
		".........oooooo.........",
		"..........o..o..........",
		".........o....o.........",
		"........o......o........",
		"................o.......",
		"........................",
		"........................",
	],
}

const PROP_PALETTES := {
	"spit": {"o": "3d1a63", "f": "c58aff", "l": "f0dcff"},
	"bolt": {"o": "07203d", "f": "5aa6ff", "l": "d8ecff"},
	"spark": {"o": "6b5405", "f": "ffd35a", "l": "fff4c2"},
	"xp_orb": {"o": "0d4a2b", "f": "50f59e", "l": "d8ffe8"},
	"coin": {"o": "6b4a05", "f": "ffc93c", "l": "fff0b8"},
}

const PROP_ROWS := {
	"spit": [
		"..ffff..",
		".fflllf.",
		"fflllllf",
		"ffllllff",
		"ffffffff",
		".ffffff.",
		"..oooo..",
		"........",
	],
	"bolt": [
		"...ff...",
		"..fllf..",
		".fllllf.",
		"ffllllff",
		"ffllllff",
		".ffffff.",
		"..oooo..",
		"........",
	],
	"spark": [
		"...o....",
		"..off...",
		".offlf..",
		"offlllf.",
		".fllllff",
		"..fllff.",
		"...ffo..",
		"....o...",
	],
	"xp_orb": [
		"........",
		"..oooo..",
		".offffo.",
		"offllffo",
		"offllffo",
		".offffo.",
		"..oooo..",
		"........",
	],
	"coin": [
		"..oooo..",
		".offffo.",
		"offllffo",
		"ofllllfo",
		"ofllllfo",
		"offllffo",
		".offffo.",
		"..oooo..",
	],
}


## Shop-item and ability-upgrade icons, 8x8 like the props above.
const ICON_PALETTES := {
	"carapace": {"o": "3d0a12", "f": "a52f3d", "l": "ff8f7a"},
	"phase_boots": {"o": "1d4a63", "f": "8ad7ff", "l": "e6f7ff"},
	"bloodfang": {"o": "3d0a12", "f": "ff4f4f", "l": "ffb0b0"},
	"pendant": {"o": "0d2b1a", "f": "3f9e57", "l": "8fe08f"},
	"prism": {"o": "3d1a63", "f": "b06bff", "l": "e2c4ff"},
	"aegis": {"o": "6b5405", "f": "ffd35a", "l": "fff4c2"},
	"ember": {"o": "6b2f05", "f": "ff7a29", "l": "ffd0a8"},
	"frostbite": {"o": "0a2233", "f": "a8dcff", "l": "ffffff"},
	"lodestone": {"o": "0d4a44", "f": "3fd0c0", "l": "c2fff6"},
	"rapid": {"o": "6b5405", "f": "ffd35a", "l": "fff4c2"},
	"heavy": {"o": "16191f", "f": "8b96a8", "l": "dfe6f2"},
	"chain": {"o": "07203d", "f": "5aa6ff", "l": "d8ecff"},
	"boots": {"o": "3a4152", "f": "8f9bb3", "l": "dfe6f2"},
	"vitality": {"o": "3d0a12", "f": "ff8f7a", "l": "ffe0d0"},
	"plating": {"o": "16191f", "f": "626d80", "l": "8b96a8"},
	"reach": {"o": "2a1405", "f": "e0a44b", "l": "ffd08a"},
	"flow": {"o": "0d2b1a", "f": "3f9e57", "l": "8fe08f"},
	"choir": {"o": "3a6130", "f": "e8c25a", "l": "fff3cf"},
	"depth": {"o": "0a2233", "f": "3aa9e0", "l": "9fe3ff"},
	"shatter": {"o": "0a2233", "f": "a8dcff", "l": "ffffff"},
}

const ICON_ROWS := {
	"carapace": [
		"...oo...",
		"..offo..",
		".offlfo.",
		"offlllfo",
		"offlllfo",
		".offffo.",
		"..offo..",
		"...oo...",
	],
	"phase_boots": [
		"..ff....",
		"..ff....",
		"..ff....",
		"..ffoo..",
		"..ffooo.",
		".fffffoo",
		"offffooo",
		"oooooooo",
	],
	"bloodfang": [
		"..ff....",
		".ffff...",
		".ffff...",
		".ffff...",
		".fllf...",
		"..ff....",
		"..ff....",
		"...o....",
	],
	"pendant": [
		"........",
		".ff..ff.",
		"ffllfflf",
		"ffllllff",
		".ffllff.",
		"..ffff..",
		"...ff...",
		"........",
	],
	"prism": [
		"...ff...",
		"..ffff..",
		".ffllff.",
		"ffllllff",
		".ffllff.",
		"..ffff..",
		"...ff...",
		"........",
	],
	"aegis": [
		"..oooo..",
		".offffo.",
		"of.ll.fo",
		"offllffo",
		"of.ll.fo",
		".offffo.",
		"..offo..",
		"...oo...",
	],
	"ember": [
		"...f....",
		"..fff...",
		".fflff..",
		".ffffo..",
		"..ffff..",
		"..lfff..",
		"..offf..",
		"...oo...",
	],
	"frostbite": [
		"..f..f..",
		"...ff...",
		"f.ffff.f",
		".ffllff.",
		"f.ffff.f",
		"...ff...",
		"..f..f..",
		"........",
	],
	"lodestone": [
		"ff....ff",
		"ff....ff",
		"ff....ff",
		"ff....ff",
		"lf....fl",
		"lf....fl",
		".ffffff.",
		"..oooo..",
	],
	"rapid": [
		"f.f.....",
		"ff.ff...",
		".ff.ff..",
		"..ff.ff.",
		".ff.ff..",
		"ff.ff...",
		"f.f.....",
		"........",
	],
	"heavy": [
		"..ffff..",
		".ffffff.",
		"ffffffff",
		"ffllllff",
		"ffllllff",
		"..ffff..",
		"..o..o..",
		"..o..o..",
	],
	"chain": [
		".ff..ff.",
		"f..ff..f",
		"f..ff..f",
		".ff..ff.",
		".ff..ff.",
		"f..ff..f",
		"f..ff..f",
		".ff..ff.",
	],
	"boots": [
		"..ff....",
		"..ff....",
		"..ff....",
		"..ffoo..",
		"..ffooo.",
		".fffffoo",
		"offffooo",
		"oooooooo",
	],
	"vitality": [
		"........",
		".ff..ff.",
		"ffllfflf",
		"ffllllff",
		".ffllff.",
		"..ffff..",
		"...ff...",
		"........",
	],
	"plating": [
		"..oooo..",
		".ffffff.",
		".llllll.",
		".ffffff.",
		".llllll.",
		".ffffff.",
		"..oooo..",
		"........",
	],
	"reach": [
		"......f.",
		".....ff.",
		"....fff.",
		"...ff...",
		"..ff....",
		".ff.....",
		"ff......",
		"o.......",
	],
	"flow": [
		"...f....",
		"..fff...",
		".fllff..",
		".fllff..",
		".ffffo..",
		"..ffo...",
		"...o....",
		"........",
	],
	"choir": [
		"....f...",
		"....f...",
		"....f...",
		"....f...",
		"..fff...",
		".fofof..",
		".fofof..",
		"..ooo...",
	],
	"depth": [
		"f.....f.",
		".f...f..",
		"..f.f...",
		"...f....",
		"f.....f.",
		".f...f..",
		"..f.f...",
		"...f....",
	],
	"shatter": [
		"f...f...",
		".f.f.f..",
		"..fff...",
		".fffff..",
		"..fff...",
		".f.f.f..",
		"f...f...",
		"........",
	],
}


const TERRAIN_PALETTES := {
	"grass_tile": {"a": "26401f", "b": "2f4f26", "c": "3a6130", "d": "47743a"},
	"grass_tuft": {"c": "3a6130", "d": "47743a", "l": "5c8f47"},
	"grass_flower": {"c": "3a6130", "d": "47743a", "p": "d86f9b", "w": "ffe9f2"},
	"grass_bloom": {"c": "3a6130", "d": "47743a", "y": "e8c25a", "w": "fff3cf"},
	"rock_small": {"o": "16191f", "s": "424b58", "m": "626d80", "h": "8b96a8", "g": "3f6a37"},
	"rock_large": {"o": "16191f", "s": "424b58", "m": "626d80", "h": "8b96a8", "g": "3f6a37"},
	"boulder": {"o": "16191f", "s": "424b58", "m": "626d80", "h": "8b96a8", "g": "3f6a37"},
	"spire": {"o": "0d2230", "s": "1f5f7a", "m": "2f8fb0", "h": "7fd8f0", "w": "e8fbff"},
}

## The ground tile is deliberately featureless at its edges so it repeats without
## a visible seam. All the character comes from the decals scattered on top.
const TERRAIN_ROWS := {
	"grass_tile": [
		"bcbbabbcbbabbcbb",
		"bbbccbbbbcbbbbab",
		"abbbbbabcbbbdbbb",
		"bbcbbbbbbbbabbcb",
		"bbbabdbbcbbbbbbb",
		"cbbbbbbbabbbcbba",
		"bbbcbabbbbcbbbbb",
		"abbbbbcbbbabbcbb",
		"bbcbbbbbbbdbbbba",
		"bbbbabbcbbbbabbb",
		"cbbbdbbbbabbbcbb",
		"bbabbbbcbbbbbbba",
		"bbbbcbabbbcbbcbb",
		"abbbbbbbbbbabbbb",
		"bbcbbabdbbbbcbba",
		"bbbbbbbbabbbbbbb",
	],
	"grass_tuft": [
		"........",
		"...l....",
		"..l.l.l.",
		"..ldl.l.",
		".ldcdll.",
		".dcccdd.",
		"..ccc...",
		"........",
	],
	"grass_flower": [
		"........",
		"...p....",
		"..pwp...",
		"...p.p..",
		"...d.p..",
		"..dcd...",
		"...c....",
		"........",
	],
	"grass_bloom": [
		"........",
		"..y.y...",
		"..ywy...",
		"...y.y..",
		"...d.y..",
		"..dcdd..",
		"...cc...",
		"........",
	],
	"rock_small": [
		"................",
		"................",
		"......oooo......",
		".....omhhmo.....",
		"....omhhhhmo....",
		"...omhhmmmmmo...",
		"..omhhmmmmmmmo..",
		"..omhmmmssmmmo..",
		".omhmmmsssssmo..",
		".omgmmsssssssmo.",
		".oggmssssssssso.",
		"..ogssssssssso..",
		"...oosssssoo....",
		".....oooooo.....",
		"................",
		"................",
	],
	"rock_large": [
		"................",
		"....oo....oo....",
		"...omho..omhmo..",
		"..omhhmo.omhhmo.",
		"..omhhmmoomhhmmo",
		".omhhmmmmmmhmmmo",
		".omhmmmmmmmmmmmo",
		"omhmmmsssmmmmmmo",
		"omhmmsssssssmmmo",
		"omgmmsssssssssmo",
		"oggmssssssssssso",
		"ogmsssssssssssso",
		".ossssssssssssso",
		".oosssssssssssoo",
		"..oooosssssoooo.",
		"......oooooo....",
	],
	"boulder": [
		"........................",
		"..........oooo..........",
		".......ooomhhmooo.......",
		".....oomhhhhhhhhmoo.....",
		"....omhhhhhhhhhhhhmo....",
		"...omhhhhmmmmmmhhhhmo...",
		"..omhhhmmmmmmmmmmhhhmo..",
		"..omhhmmmmmmmmmmmmmhmo..",
		".omhhmmmmmssssmmmmmmmo..",
		".omhmmmmssssssssmmmmmo..",
		".omhmmmssssssssssmmmmmo.",
		".omhmmssssssssssssmmmmo.",
		".omgmssssssssssssssmmmo.",
		".omgmsssssssssssssssmmo.",
		".oggmssssssssssssssssmo.",
		".oggsssssssssssssssssso.",
		"..ogsssssssssssssssssso.",
		"..ooosssssssssssssssoo..",
		"...ooosssssssssssssoo...",
		".....ooossssssssoooo....",
		".......ooossssooo.......",
		".........oooooo.........",
		"........................",
		"........................",
	],
	"spire": [
		"........................",
		"..........ow............",
		".........omwo...........",
		".........omwo..o........",
		"........osmwo.ow........",
		"........osmwo.omo.......",
		"........osmwoosmo.......",
		".......oosmwoosmo.......",
		"...o...osmmwoosmo.......",
		"..ow...osmmwoosmo..o....",
		"..omo..osmmwoosmo.ow....",
		"..omo.oosmmwoosmoosmo...",
		"..smo.osmmmwoosmoosmo...",
		"..smoosmmmmwoosmmosmo...",
		"..smoosmmmmwoosmmosmo...",
		"..smoosmmmmwoosmmosmo...",
		"..ssoosmmmmwoosmmosso...",
		"..ssoossmmmwoossmosso...",
		"...soossmmmwoossmosso...",
		"...ssoossmmwoossmosso...",
		"....soossssoossssoss....",
		"....ooosssoossssooo.....",
		"......oooooooooo........",
		"........................",
	],
}


static func all_sprites() -> Dictionary:
	var sprites: Dictionary = {}
	_collect(sprites, HERO_ROWS, HERO_PALETTES)
	_collect(sprites, ENEMY_ROWS, ENEMY_PALETTES)
	_collect(sprites, BOSS_ROWS, BOSS_PALETTES)
	_collect(sprites, PROP_ROWS, PROP_PALETTES)
	_collect(sprites, ICON_ROWS, ICON_PALETTES)
	_collect(sprites, TERRAIN_ROWS, TERRAIN_PALETTES)
	return sprites


static func _collect(sprites: Dictionary, rows_by_name: Dictionary, palettes: Dictionary) -> void:
	for sprite_name in rows_by_name:
		sprites[sprite_name] = {
			"rows": rows_by_name[sprite_name],
			"palette": palettes[sprite_name],
		}


## Returns a human readable problem per malformed sprite, so the forge and the
## smoke test can both refuse to ship broken art.
static func validation_errors() -> Array[String]:
	var errors: Array[String] = []
	for sprite_name in all_sprites():
		var sprite: Dictionary = all_sprites()[sprite_name]
		var rows: Array = sprite.rows
		var palette: Dictionary = sprite.palette
		var height := rows.size()
		if height == 0:
			errors.append("%s has no rows" % sprite_name)
			continue
		for row_index in height:
			var row: String = rows[row_index]
			if row.length() != height:
				errors.append("%s row %d is %d wide but the grid is %d tall" % [sprite_name, row_index, row.length(), height])
			for character in row:
				if character != "." and not palette.has(character):
					errors.append("%s uses '%s' which is not in its palette" % [sprite_name, character])
	return errors
