"""One-shot generator for per-ABILITY sound banks (T3.8 follow-up: "true 64+").

Every ability in the roster gets its OWN unique procedural SFX so that, within a
single hero, no two abilities sound identical. Each bank is synthesized
procedurally (stdlib only: math/random/wave) -- MIT-safe, no sampled assets --
and is derived from a (hero, archetype) base recipe plus a *deterministic*
per-ability variation (pitch offset, extra partial layer, and a seeded timbre
jitter) so the output is stable across runs while still distinct per ability.

The base recipe is chosen from the hero's element (to match the hero's existing
cast_<hero> / attack_<hero> banks already generated by synth_themes.py) crossed
with the ability's archetype family. The per-ability variation guarantees that,
e.g., tobor_steam_keg and tobor_keg_lob -- both NUKE_BOLT, both tobor -- do NOT
sound the same.

Output: assets/audio/themes/ability_<ability_id>.wav  (one file per ability)

Regenerate everything:
    python tools/synth_abilities.py

The audio_service.gd registers these banks under the id "ability_<ability_id>"
and play_ability() resolves each ability to its own bank, falling back to the
shared cast_<hero> bank, then the archetype family, then a warning.
"""

import hashlib
import math
import os
import random
import sys
import wave

# Reuse the exact synth engine + hero element recipes from synth_themes.py so the
# per-ability banks sit in the same sonic world as the existing cast/attack banks.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from synth_themes import RECIPES, render_layer, synthesize, write_wav, MIX_RATE, FADE_MS  # noqa: E402

OUT_DIR = os.path.join("assets", "audio", "themes")

# Ability ids in the roster, grouped by hero (from player_class.gd). The hero key
# maps to a synth_themes.py RECIPES entry (the element base) where one exists.
# Note: "frostbinder" in RECIPES is the removed ice hero; rime uses it as base.
HERO_BASE = {
    "arclight": "arclight",
    "astral": "astral",
    "bulwark": "bulwark",
    "cinder": "cinder",
    "ember": "ember",
    "nebula": "nebula",
    "pyra": "pyra",
    "rime": "frostbinder",
    "sage": "sage",
    "slag": "slag",
    "stump": "stump",
    "thorn": "thorn",
    "tobor": "tobor",
    "volt": "volt",
    "warden": "warden",
    "willow": "willow",
}

# Archetype -> a short, punchy "flavour" layer appended to the hero base take so
# an ability reads as its family (nuke/blast, heal, shield, dash, etc.) on top of
# the hero's element. This is what makes cinder_dragon_fire (NUKE_BOLT) feel like a
# fire-bolt rather than a plain chime, while cinder_fiery_assault (RADIUS_BURST)
# feels like an area burst.
ARCHETYPE_FLAVOUR = {
    "NUKE_BOLT":     [dict(wave="zap_noise", f0=2200, f1=600, dur=0.18, amp=0.22)],
    "CHAIN_NUKE":    [dict(wave="zap_noise", f0=3000, f1=900, dur=0.14, amp=0.20)],
    "CONE_BURST":    [dict(wave="whoosh", f0=900, f1=300, dur=0.22, amp=0.30)],
    "RADIUS_BURST":  [dict(wave="sine", f0=320, f1=90, dur=0.30, amp=0.42)],
    "DASH_STRIKE":   [dict(wave="whoosh", f0=1400, f1=400, dur=0.20, amp=0.34)],
    "BLINK":         [dict(wave="chime", f0=1800, f1=1100, dur=0.16, amp=0.28, partials=[1.0, 2.0])],
    "SELF_HEAL":     [dict(wave="chime", f0=1200, f1=1700, dur=0.28, amp=0.30, partials=[1.0, 1.5, 2.0])],
    "AOE_HEAL":      [dict(wave="chime", f0=1000, f1=1500, dur=0.34, amp=0.32, partials=[1.0, 1.26, 2.0])],
    "SHIELD_BURST":  [dict(wave="square", f0=220, f1=140, dur=0.26, amp=0.34, duty=0.3)],
    "BUFF_SELF":     [dict(wave="chime", f0=900, f1=1200, dur=0.24, amp=0.28, partials=[1.0, 1.5])],
    "PUSH_PULL_BURST": [dict(wave="whoosh", f0=500, f1=180, dur=0.30, amp=0.40)],
    "STORM_PULL":    [dict(wave="sine", f0=700, f1=160, dur=0.30, amp=0.36)],
    "ZONE_CHANNEL":  [dict(wave="sine", f0=400, f1=560, dur=0.34, amp=0.30, partials=[1.0, 1.5])],
    "SUMMON_SPIRIT": [dict(wave="chime", f0=1500, f1=900, dur=0.30, amp=0.30, partials=[1.0, 1.5, 2.0])],
    "SLAM_TAUNT":    [dict(wave="square", f0=120, f1=60, dur=0.34, amp=0.44, duty=0.4)],
    "PIT_SLOW":      [dict(wave="chime", f0=1400, f1=700, dur=0.30, amp=0.30, partials=[1.0, 2.0])],
    "ATTACK_FURY":   [dict(wave="saw", f0=200, f1=400, dur=0.24, amp=0.34)],
    "SPAWN_WALL":    [dict(wave="square", f0=90, f1=50, dur=0.30, amp=0.42, duty=0.35)],
    "AREA_BOUNCE":   [dict(wave="chime", f0=1600, f1=500, dur=0.22, amp=0.30, partials=[1.0, 2.0, 2.5])],
}

# Fallback flavour for archetypes not in ARCHETYPE_FLAVOUR (defensive).
_DEFAULT_FLAVOUR = [dict(wave="chime", f0=1000, f1=700, dur=0.22, amp=0.26, partials=[1.0, 1.5])]


def _seed(ability_id: str) -> int:
    """Deterministic 32-bit seed from the ability id (stable across runs)."""
    return int(hashlib.sha256(ability_id.encode("utf-8")).hexdigest()[:8], 16)


def _pitch_offset(ability_id: str) -> float:
    """Per-ability pitch offset in [0.92, 1.10] so same-hero same-archetype abilities
    never land on an identical pitch. Applied to every layer of the take."""
    norm = (_seed(ability_id) % 1000) / 1000.0
    return 0.92 + 0.18 * norm


def build_ability_take(ability_id: str, archetype: str) -> list:
    hero = ability_id.split("_")[0]
    base_hero = HERO_BASE.get(hero, "astral")
    base_recipes = RECIPES.get(base_hero, RECIPES["astral"])
    # Pick one of the hero's existing base takes (deterministically per ability)
    # so each ability inherits a slightly different element flavour too.
    base_take = base_recipes[_seed("base:" + ability_id) % len(base_recipes)]
    flavour = ARCHETYPE_FLAVOUR.get(archetype, _DEFAULT_FLAVOUR)

    # Clone the base layers and shift them down a touch (the hero base is the
    # "identity" carrier), then append the archetype flavour on top.
    layers = []
    for layer in base_take:
        l = dict(layer)
        l["f0"] = float(l.get("f0", 440)) * 0.85
        l["f1"] = float(l.get("f1", 440)) * 0.85
        l["amp"] = float(l.get("amp", 0.4)) * 0.85
        layers.append(l)
    for fl in flavour:
        fl2 = dict(fl)
        fl2["dur"] = float(fl2.get("dur", 0.2)) * 0.9
        layers.append(fl2)

    # Apply the per-ability pitch offset to all layers.
    po = _pitch_offset(ability_id)
    for l in layers:
        l["f0"] = float(l["f0"]) * po
        l["f1"] = float(l["f1"]) * po
    return layers


def main() -> int:
    os.makedirs(OUT_DIR, exist_ok=True)
    # Read the ability roster straight from player_class.gd so the generator and
    # the game always agree on the ability set (no hand-maintained list).
    import re
    gd_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "scripts", "player_class.gd")
    s = open(gd_path, encoding="utf-8").read()
    pat = re.compile(
        r'^\t"([a-z_]+)": \{\n\s*"name":\s*".*?",\s*"archetype":\s*Archetype\.([A-Z_]+)',
        re.M,
    )
    abilities = [(m.group(1), m.group(2)) for m in pat.finditer(s)]
    if not abilities:
        print("ERROR: no abilities found in player_class.gd", file=sys.stderr)
        return 1

    written = 0
    for ability_id, archetype in abilities:
        layers = build_ability_take(ability_id, archetype)
        rng = random.Random(_seed("render:" + ability_id))
        pcm = synthesize(layers, rng)
        out_path = os.path.join(OUT_DIR, "ability_" + ability_id + ".wav")
        write_wav(out_path, pcm)
        written += 1
    print("synth_abilities: %d ability wavs written to %s" % (written, OUT_DIR))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
