class_name ToborWorldArt
extends RefCounted

## SuperMercator robots and biome tiles. SpriteArt prefixes every id with tw_.

## Global terrain tone knob. The biome tiles shipped saturated (electric oranges,
## teal, pure blues); the player asked for the old, muted grass-meadow feel. TERRAIN_SAT_
## ADJUST scales every tile/void/decal/rock palette's saturation toward gray before the
## sprites are registered, so a single constant retunes the whole world without hand-
## editing each palette. 1.0 = original, 0.0 = grayscale. Grass meadow tiles are
## authored separately and skip this. 0.48 mutes volcano/ice/factory/docks ground.
const TERRAIN_SAT_ADJUST := 0.48
## Extra mute for walkable floor / void only, so heroes and enemies stay punchy.
const GROUND_SAT_ADJUST := 0.28
## Matching luminance lift so muting doesn't read as darkening the world. 0 = keep.
const TERRAIN_LIGHT_ADJUST := 0.08

const ENEMY_PALETTES := {
	"grunt": {"o": "1a1210", "f": "8b95a1", "l": "dfe6f2", "e": "181410", "w": "3a4656", "g": "e85a2a"},
	"swarmling": {"o": "1a1210", "f": "e85a2a", "l": "ffe08c", "e": "181410", "w": "dfe6f2"},
	"spitter": {"o": "1a1210", "f": "3a4656", "l": "7fd4ff", "e": "e82e26", "w": "dfe6f2", "g": "4f8fe0"},
	"drifter": {"o": "1a1210", "f": "8b95a1", "l": "dfe6f2", "e": "181410", "w": "f2f4f0", "g": "4f8fe0"},
	"brute": {"o": "1a1210", "f": "c43018", "l": "ffe08c", "e": "181410", "w": "5a6270", "s": "3a4656", "h": "dfe6f2"},
	"stalker": {"o": "1a1210", "f": "e85a2a", "l": "f2f4f0", "e": "181410", "w": "4f8fe0"},
	"bomber": {"o": "1a1210", "f": "e82e26", "l": "ffe14a", "e": "181410", "w": "f2f4f0"},
	"hexer": {"o": "1a1210", "f": "3a4656", "l": "50f59e", "e": "181410", "w": "dfe6f2", "g": "7fd4ff"},
	"sentinel": {"o": "1a1210", "f": "5a6270", "l": "dfe6f2", "e": "e82e26", "w": "8b95a1", "g": "ffe14a"},
	"splitter": {"o": "1a1210", "f": "4f8fe0", "l": "d8ecff", "e": "181410", "w": "f2f4f0", "g": "50f59e"},
	"charger": {"o": "1a1210", "f": "e85a2a", "l": "f2f4f0", "e": "181410", "w": "4f8fe0", "g": "e82e26"},
	"summoner": {"o": "1a1210", "f": "c43018", "l": "f2f4f0", "e": "181410", "w": "6d7680", "g": "ffe14a"},
	"lurker": {"o": "2a2010", "f": "c9a227", "l": "ffe08c", "e": "181410", "w": "f2f4f0"},
}

const ENEMY_ROWS := {
	"grunt": [
		"................",
		"..oooooooooooo..",
		"..ol.l.l.l.llo..",
		"..ol.l.l.l.llo..",
		"..olgggggggglo..",
		"..ollllllllllo..",
		"..oooooooooooo..",
		"..ow........wo..",
		"..owwwwwwwwwwo..",
		"...o.o....o.o...",
		"...oo......oo...",
		"..oo........oo..",
		"................",
		"................",
		"................",
		"................",
	],
	"swarmling": [
		".w...w....w...w.",
		"..w.oooooooo.w..",
		".wo.offffffo.ow.",
		"..o.ofleeelfo.o.",
		".wo.offffffo.ow.",
		"..o.offllllfo.o.",
		".w.o.offffo.o.w.",
		"w.o...oooo...o.w",
		".w.o.o....o.o.w.",
		"..w.o......o.w..",
		".w.w........w.w.",
		"..w..........w..",
		"................",
		"................",
		"................",
		"................",
	],
	"spitter": [
		".......gg.......",
		"......gllg......",
		".....gllelg.....",
		".....gllllg.....",
		"......oooo......",
		".....offffo.....",
		"....offffffo..o.",
		"...owwwwwwwoofo.",
		"...ow......wooo.",
		"...oo......oo...",
		"..oo........oo..",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"drifter": [
		"ww............ww",
		".w....oooo....w.",
		"w....offffo....w",
		"....ofleeelfo...",
		"....offffffo....",
		".....oggggo.....",
		"......oooo......",
		".....o....o.....",
		"....o......o....",
		"...o........o...",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"brute": [
		"ss..............",
		"ss....oooo......",
		"sso..ohhhho.....",
		"ossoohhhhhho....",
		"oossohhhhhho....",
		".oosohhhhhho....",
		"..oswwwwwwwo....",
		"..oswfffffwso...",
		"..oswfeefwso....",
		"..oswwwwwwso....",
		"...ossoosso.....",
		"...oooooooo.....",
		"..oo......oo....",
		"................",
		"................",
		"................",
	],
	"stalker": [
		"................",
		"................",
		"...oooooooooo...",
		"...ofllllllfo...",
		"...ofleeeelfo...",
		"...offfffffo....",
		"wwwwwwwwwwwwwwww",
		"w..............w",
		".wwwwwwwwwwwwww.",
		"..o.o......o.o..",
		"...oo......oo...",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"bomber": [
		"................",
		".........ll.....",
		"........l.l.....",
		".......l........",
		".....oooooo.....",
		"....offffffo....",
		"...offwweewfo...",
		"...offwwwwffo...",
		"...offfffffo....",
		"....ooooooo.....",
		".....o...o......",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"hexer": [
		".......gg.......",
		"......gllg......",
		".....gllllg.....",
		"....oooooooo....",
		"...owwwwwwwwo...",
		"...owlgggglwo...",
		"...owllllllwo...",
		"...owleeeelwo...",
		"...owfffffo.....",
		"....owwwwwwo....",
		"....oo....oo....",
		"...oo......oo...",
		"................",
		"................",
		"................",
		"................",
	],
	"sentinel": [
		"......gggg......",
		".....gwwwg......",
		"....gwleewg.....",
		"....gwwwwwg.....",
		".....oooo.......",
		"......oo........",
		".....offfo......",
		"....offffffo....",
		"...ow......wo...",
		"...oo......oo...",
		"..oo........oo..",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"splitter": [
		"................",
		"....oooooooo....",
		"...oggggggggo...",
		"...ollllllllo...",
		"...olffeefflo...",
		"...ollllllllo...",
		"....oooooooo....",
		"....ollllllo....",
		"...olfffffflo...",
		"...olfffffflo...",
		"....oooooooo....",
		".....o....o.....",
		"....oo....oo....",
		"................",
		"................",
		"................",
	],
	"charger": [
		"......gggg......",
		".....gllllg.....",
		"....glleelg.....",
		"....glllllg.....",
		"...offfffffo....",
		"..offffffffffo..",
		"wwwwwwwwwwwwwwww",
		"woooooooooooooow",
		".wwwwwwwwwwwwww.",
		"..o.o......o.o..",
		"...oo......oo...",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"summoner": [
		"......gggg......",
		".....gllllg.....",
		"....glleelg.....",
		"...gglllllgg....",
		"...goffffog.....",
		"..ogooooooogo...",
		"..ogffffffgo....",
		"...owwwwwwo.....",
		".o..owwwwo..o...",
		"olo.owwwwo.olo..",
		".o..oo..oo..o...",
		"....oo..oo......",
		"...oo....oo.....",
		"................",
		"................",
		"................",
	],
	"lurker": [
		"................",
		"...oooooooooo...",
		"...offffffffo...",
		"...ofllllllfo...",
		"...ofleeeelfo...",
		"...ofllllllfo...",
		"...offffffffo...",
		"...offffffffo...",
		"...offffffffo...",
		"...oooooooooo...",
		"....o......o....",
		"...oo......oo...",
		"................",
		"................",
		"................",
		"................",
	],
}

const BOSS_PALETTES := {
	"ravager": {"o": "1a0808", "f": "c43018", "l": "f2f4f0", "e": "181410", "w": "5a6270", "g": "e82e26", "s": "3a4656"},
	"stormcaller": {"o": "101418", "f": "8b95a1", "l": "f2f4f0", "e": "181410", "w": "dfe6f2", "g": "e82e26", "y": "ffe14a"},
}

const BOSS_ROWS := {
	"ravager": [
		"ss......gggg......ss....",
		"sso....gllllg....oss....",
		"osso..glleelg...osso....",
		"oosso.glllllg..ossoo....",
		".oosofffffffoossoo......",
		".oosoffffffffosso.......",
		"oosfffffffffffooso......",
		"oosffffffffffffffso.....",
		"ossffffffffffffffss.....",
		"osssffffffffffffssso....",
		"ossoffffffffffffosso....",
		"oossoffffffffffossoo....",
		".oosswwwwwwwwwssoo......",
		"..oswwwwwwwwwwso........",
		"..osww......wwso........",
		"..oswgg....ggwso........",
		"..ossog....gosso........",
		"..oooo......oooo........",
		".oo............oo.......",
		"oo..............oo......",
		"o................o......",
		"........................",
		"........................",
		"........................",
	],
	"stormcaller": [
		"ww......oooooo......ww..",
		".w.....oyyyyyyo......w..",
		"w.....oylleellyo......w.",
		".....oylllllllyo........",
		"......offffffffo........",
		".....offggggfffo........",
		"......owwwwwwwwo........",
		".....oowwwwwwwoo........",
		"....o..owwwwwwo..o......",
		"...o....o....o....o.....",
		"..ww...o......o...ww....",
		".w....o........o....w...",
		"w....ww........ww....w..",
		"....w............w......",
		"...w..............w.....",
		"..w................w....",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
	],
}

const PROP_PALETTES := {
	"spit": {"o": "07203d", "f": "4f8fe0", "l": "d8ecff"},
	"bolt": {"o": "3a2008", "f": "ff7a29", "l": "ffe08c"},
	"spark": {"o": "6b1408", "f": "e82e26", "l": "ffe14a"},
	"xp_orb": {"o": "6b2f05", "f": "e85a2a", "l": "ffe08c"},
	"coin": {"o": "6b4a05", "f": "ffc93c", "l": "fff0b8"},
}

const PROP_ROWS := {
	"spit": [
		"...ff...",
		"..fllf..",
		".ffllff.",
		"ffffffff",
		".ffooff.",
		"..oooo..",
		"........",
		"........",
	],
	"bolt": [
		"f......f",
		".f.ff.f.",
		"..fllf..",
		".ffllff.",
		"..fllf..",
		".f.ff.f.",
		"f......f",
		"........",
	],
	"spark": [
		"...l....",
		"..flf...",
		".fflff..",
		"lfffffl.",
		".fflff..",
		"..flf...",
		"...o....",
		"........",
	],
	"xp_orb": [
		"........",
		"..oooo..",
		".offffo.",
		"offllffo",
		"offllffo",
		".offffo.",
		"..oooo..",
		"........",
	],
	"coin": [
		"..oooo..",
		".offffo.",
		"offllffo",
		"ofllllfo",
		"ofllllfo",
		"offllffo",
		".offffo.",
		"..oooo..",
	],
}

const _TILE := [
	"bcbbabbcbbabbcbb",
	"bbbccbbbbcbbbbab",
	"abbbbbabcbbbdbbb",
	"bbcbbbbbbbbabbcb",
	"bbbabdbbcbbbbbbb",
	"cbbbbbbbabbbcbba",
	"bbbcbabbbbcbbbbb",
	"abbbbbcbbbabbcbb",
	"bbcbbbbbbbdbbbba",
	"bbbbabbcbbbbabbb",
	"cbbbdbbbbabbbcbb",
	"bbabbbbcbbbbbbba",
	"bbbbcbabbbcbbcbb",
	"abbbbbbbbbbabbbb",
	"bbcbbabdbbbbcbba",
	"bbbbbbbbabbbbbbb",
]
const _FACTORY_TILE := [
	"abababababababab",
	"babcbabababababa",
	"abababababcbabab",
	"babababababababa",
	"ababcbababababab",
	"babababababcbaba",
	"abababababababab",
	"babababcbabababa",
	"abababababababab",
	"babcbabababababa",
	"abababababcbabab",
	"babababababababa",
	"ababcbababababab",
	"babababababcbaba",
	"abababababababab",
	"babababababababa",
]
const _DOCKS_TILE := [
	"bbbbbbbbbbbbbbbb",
	"acacacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacacacaca",
	"bbbbbbbbbbbbbbbb",
	"acacacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacacacaca",
	"bbbbbbbbbbbbbbbb",
	"acacacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacacacaca",
	"bbbbbbbbbbbbbbbb",
	"acacacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacacacaca",
]

const TERRAIN_PALETTES := {
	"grass_tile": {"a": "5c5044", "b": "6e5e4e", "c": "4a4038", "d": "e08a3a"},
	"grass_tuft": {"c": "3a3028", "d": "2a2018", "l": "c45a20"},
	"grass_long": {"c": "3a3028", "d": "2a2018", "l": "c45a20", "h": "e85a2a"},
	"grass_flower": {"c": "6e5e4e", "d": "e8e4d8", "p": "f6f1e4", "w": "ffffff"},
	"grass_bloom": {"c": "6e5e4e", "d": "c43018", "y": "e85a2a", "w": "ffe08c"},
	"tree_oak": {"o": "1a140c", "t": "6b4a2c", "s": "3a2818", "m": "2f5a28", "l": "4a8a38", "h": "7ab84a", "g": "3f6a37"},
	"tree_pine": {"o": "14180c", "t": "5a3c22", "s": "2a2010", "m": "1e4a24", "l": "2f6a30", "h": "5a9a40", "w": "e8f0d8", "g": "163818"},
	"tree_dead": {"o": "1a0c08", "t": "4a2a18", "s": "2a1810", "m": "3a2214", "l": "6b3a20", "h": "c45a20", "w": "ffe08c"},
	"tree_pipe": {"o": "101418", "t": "3a4656", "s": "1a1e24", "m": "5a6270", "l": "8b95a1", "h": "2bbfbe", "w": "e85a2a"},
	"tree_piling": {"o": "1a1210", "t": "6b4a1a", "s": "3a2a10", "m": "8a6230", "l": "c9a227", "h": "2f8fb0", "w": "dfe6f2"},
	"tree_willow": {"o": "1a140c", "t": "6b4a2c", "s": "3a2818", "m": "2f5a28", "l": "4a8a38", "h": "7ab84a", "g": "3f6a37"},
	"tree_round": {"o": "1a140c", "t": "6b4a2c", "s": "3a2818", "m": "2f5a28", "l": "4a8a38", "h": "7ab84a", "g": "3f6a37"},
	"tree_fir": {"o": "14180c", "t": "5a3c22", "s": "2a2010", "m": "1e4a24", "l": "2f6a30", "h": "5a9a40", "w": "e8f0d8", "g": "163818"},
	"tree_palm": {"o": "1a140c", "t": "8a6230", "s": "3a2818", "m": "2f5a28", "l": "4a8a38", "h": "7ab84a", "g": "c9a227"},
	"tree_cypress": {"o": "14180c", "t": "5a3c22", "s": "2a2010", "m": "1e4a24", "l": "2f6a30", "h": "5a9a40", "g": "3f6a37"},
	"tree_maple": {"o": "1a140c", "t": "6b4a2c", "s": "3a2818", "m": "7a4a18", "l": "c45a20", "h": "e08a3a", "g": "3f6a37"},
	"lava_chunk": {"o": "1a0808", "s": "3a1410", "m": "c43018", "h": "e85a2a", "g": "ff7a29", "w": "ffe14a"},
	"ice_crystal": {"o": "3a5068", "s": "7aa0b8", "m": "b8d4e8", "h": "e8f6ff", "g": "ffffff", "w": "d0e8f6"},
	"crate_box": {"o": "101418", "s": "3a3a40", "m": "5a6270", "h": "8b95a1", "g": "2bbfbe", "w": "e85a2a"},
	"barrel_keg": {"o": "1a1210", "s": "3a2a10", "m": "6b4a1a", "h": "c9a227", "g": "2f8fb0", "w": "dfe6f2"},
	"bollard": {"o": "1a1210", "t": "6b4a1a", "s": "3a2a10", "m": "8a6230", "l": "c9a227", "h": "2f8fb0", "w": "dfe6f2", "g": "dfe6f2"},
	"vent_cap": {"o": "101418", "s": "3a3a40", "m": "5a6270", "h": "8b95a1", "g": "2bbfbe", "w": "e85a2a"},
	"rock_jagged": {"o": "1a1210", "s": "6b4a1a", "m": "c9a227", "h": "ffe08c", "g": "3a2a10"},
	"grass_wild": {"c": "3a3028", "d": "2a2018", "l": "c45a20", "h": "e85a2a"},
	"flower_patch": {"c": "6e5e4e", "d": "e8e4d8", "p": "f6f1e4", "w": "ffffff", "y": "e85a2a"},
	"rock_small": {"o": "1a1210", "s": "6b4a1a", "m": "c9a227", "h": "ffe08c", "g": "3a2a10"},
	"rock_large": {"o": "121418", "s": "3a4656", "m": "5a6270", "h": "8b95a1", "g": "2bbfbe"},
	"boulder": {"o": "121418", "s": "3a2a10", "m": "6b4a1a", "h": "c9a227", "g": "2a2010"},
	"spire": {"o": "101418", "s": "3a4656", "m": "5a6270", "h": "8b95a1", "w": "ffe14a"},
	"shop_stand": {
		"o": "1a1210", "f": "e8d4a8", "t": "c43018", "l": "ffa090",
		"k": "181410", "s": "8b95a1", "m": "5a6270", "w": "e8e8e8",
		"e": "ff9a28", "y": "ffe08c", "a": "fff6c8", "r": "e85a2a",
		"c": "6b4a2c", "b": "3a2418", "u": "d0d0d0", "h": "f4f4f4",
		"i": "f2b090", "q": "6d7680", "d": "2a3038", "p": "4f8fe0",
	},
}

const TERRAIN_ROWS := {
	"grass_tile": _TILE,
	"grass_tuft": [
		"........",
		"........",
		"...l....",
		"..ldl...",
		".ldcdl..",
		"..dcd...",
		"...c....",
		"........",
	],
	"grass_long": [
		"........",
		"..h.l.h.",
		".h.l.h.l",
		".lhdhlh.",
		".ldcd.l.",
		"..dccd..",
		"...cc...",
		"........",
	],
	"grass_flower": [
		"........",
		"........",
		".pppppp.",
		".pwwwwp.",
		".pppppp.",
		"........",
		"........",
		"........",
	],
	"grass_bloom": [
		"........",
		"...y....",
		"..ywy...",
		"...y....",
		"...d....",
		"..dcd...",
		"...c....",
		"........",
	],
	"tree_oak": [
		"................................",
		"................................",
		"...............mm...............",
		".............lhhhm..............",
		"............mhhhllmg............",
		".........mhllmgllhh.lm..........",
		"........mlhhhlhmglhhlmm.........",
		"........m.llllhhlmml.lmm........",
		"........hlgmhhl.lmmmmlmm........",
		".......lhh.lhmllggmmmhlmmm......",
		"......mlllllllmmggggmllmmmm.....",
		".....mgmlhg.llgmmgggmlggmmm.....",
		".....mhhmmgmgmggm.mmmmhgmhm.....",
		".....lhhlmmm.mmmgggmmhhhlmm.....",
		".....hl.lmmmmgllggmmmllllmm.....",
		".....mllggmhmmmmmmmglmhlggm.....",
		".....mmmggmllmgmmmmggmmmggm.....",
		".......mmgmmmggmmmmggmmmm.......",
		"..........mmmmmgmmmmmm..........",
		"................................",
		"..............sggs..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............otso..............",
		".............oostoo.............",
		"................................",
	],
	"tree_pine": [
		"................................",
		"................................",
		"...............hhh..............",
		"................mh..............",
		"...............lg...............",
		"..............lmmll.............",
		"..............hlhh..............",
		".............hlhmllh............",
		"............hlhlglhmh...........",
		".............hllmmlh............",
		".............llmmlll............",
		"............lmllmlmll...........",
		"...........llllmhhlll...........",
		"..........llllmhmhhmlll.........",
		".........lllmlllmmllllml........",
		".............llmmllll...........",
		"............lmlmgmmlll..........",
		"...........mlllgmmlllm..........",
		"..........llllmmmmlmllll........",
		".........lllmllmmgllllmll.......",
		"........llmlllmmgmmlmllll.......",
		".......lmllllmsstsmllllmlll.....",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............otso..............",
		".............oostoo.............",
		"................................",
	],
	"tree_dead": [
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"..............l.h...............",
		"...............l................",
		"...............t................",
		"................................",
		"..............stts..lh..........",
		"..............stss.t............",
		"..........h...sstst.............",
		"...........ls.stts..............",
		".............tstss..............",
		"..............ssts..............",
		"..............sttsts............",
		"..............stss..t...........",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............sths..............",
		"..............stss..............",
		"..............swts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............otso..............",
		".............oostoo.............",
		"................................",
	],
	"tree_pipe": [
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"...........w.h.....w.h..........",
		"............w.......w...........",
		".........lllllll.lllllll........",
		".........hhhhhhh.hhhhhhh........",
		"..........smmms...smmms.........",
		"..........smmms...smmms.........",
		"..........smmms...smmms.........",
		"..........shhhs...shhhs.........",
		"..........smmms...smmms.........",
		"..........smmms...smmms.........",
		"..........smmms...smmms.........",
		"..........shhhs...shhhs.........",
		"..........smmms...smmms.........",
		"..........smmms...smmms.........",
		"..........smmms...smmms.........",
		"..........shhhs...shhhs.........",
		"..........smmms...smmms.........",
		"..........smmms...smmms.........",
		"..........smmms...smmms.........",
		"..........shhhs...shhhs.........",
		"..........smmms...smmms.........",
		"..........smmms...smmms.........",
		"..........smmms...smmms.........",
		"........ooooooooooooooooo.......",
		"........ooooooooooooooooo.......",
		"................................",
		"................................",
	],
	"tree_piling": [
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		".............ststts.............",
		".............ssttss.............",
		"............hhhhhhhh............",
		"............llllllll............",
		"............llllllll............",
		"............llllllll............",
		".............ststts.............",
		".............ssttss.............",
		".............sttsts.............",
		".............ststts.............",
		"............wwwwwwww............",
		"............mmmmmmmm............",
		".............ststts.............",
		".............ssttss.............",
		".............sttsts.............",
		".............ststts.............",
		"............wssttss.............",
		".............sttsts.............",
		".............ststtsl............",
		".............ssttss.............",
		".............sttsts.............",
		".............ststts.............",
		"...........h.ssttss.............",
		".............ottsto.w...........",
		"............ootsttoo............",
		"................................",
	],
	"tree_willow": [
		".............llhhgm.............",
		"............ghhhllmm............",
		".........mhhlmmlllhllm..........",
		"........mllhllhmglhhlmm.........",
		"........gllhl.hhlmmlllmm........",
		"........hlmmhllllmm.mlmm........",
		".......lhhllhm.lggmmghlmm.......",
		"......mhl.llllmggggg.llmmmg.....",
		".....mmmllgmlhg.mmggmlggmm......",
		".....ghhmmgmmmgggmmmm.hmmhm.....",
		"......hhlmmgmmmmggmmmlhhlmm.....",
		".....llllmm.mmllggmmml.llmm.....",
		".....mhlggmhgmmmm.mmlmllhgm.....",
		".....mgghgml.mmmmmgggmh.ggh.....",
		"......lhlmhmmggmmmmggmlmlhl.....",
		"......glghgmmmmmmmmgmmghglg.....",
		"......lglglh.........hlglgl.....",
		"......glglgl.........lglglg.....",
		"......lglglg..ssts...glglgl.....",
		"......glglgl..stts...lglglg.....",
		"......lglglg..stss...glglgl.....",
		"......glglgl..ssts...lglgl......",
		"......l.lgl...stts...glgl.......",
		"......g.g.g...stss....glg.......",
		"........l.l...ssts....l.l.......",
		"........g.g...stts....g.........",
		"..........l...stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............otso..............",
		".............oostoo.............",
		"................................",
	],
	"tree_round": [
		"................................",
		"................................",
		"................................",
		"................................",
		"...........mmmm...mm............",
		"..........lhhhm.lhllmg..........",
		".........lhhhllmhhhhl.m.........",
		"........mllhhlhl.hhllmg.........",
		"......hlmml.lggmlllggmhlm.......",
		".....lhhlmmmgggmm.mgglhhlmm.....",
		".....llllmmm.mmmmmgmmhl.lmm.....",
		".....ml.ggmmmgmhhm.mhmllggm.....",
		".....mmmggmhm.mggmllhmmmggm.....",
		".....mmm.mggmmllmmm.llgmmgm.....",
		".....mmmmhhlmmhhllmhhlmmm.m.....",
		"......mmlhhllmmhlmhhhllmmm......",
		".......mlllllmmhlmlllllmm.......",
		".......mhl.ggmmlgmlhlggmm.......",
		".......mmmmggmmlgmmmmggmm.......",
		"........mmm.mmmmmgmmmm.m........",
		".............mmmmmm.............",
		"................................",
		"..............sggs..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............otso..............",
		".............oostoo.............",
		"................................",
	],
	"tree_fir": [
		"................................",
		"...............hh...............",
		"...............hmh..............",
		"................mh..............",
		"...............lgmh.............",
		"..............lhhhl.............",
		".............lllmhml............",
		"...............lmll.............",
		"..............hlglh.............",
		".............hllmmlh............",
		"............hllhhlll............",
		"...........hlmlhmhmllh..........",
		"..............hlgl..............",
		".............hmlmllh............",
		"............hlllmmllh...........",
		"...........hlllmmgllm...........",
		"..........hllmlhhmmlllh.........",
		".........hlmllhhmhhllmlh........",
		".............lmlmlll............",
		"............llllmmll............",
		"...........llllmgmllml..........",
		"..........lllmlgmmmllll.........",
		".........llmllsttslllml.........",
		"........lmllllstssmmllllm.......",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............otso..............",
		".............oostoo.............",
		"................................",
	],
	"tree_palm": [
		"................................",
		"................................",
		"................................",
		"................................",
		"..................mm............",
		".............ml..lgg.mmm........",
		".............gg..ggllggg........",
		"..............hhhhllllmm........",
		".............hhhhhhlllgg........",
		".............hhhhhhlggmmmm......",
		".............lhhhhglmmgggg......",
		".............g..gm.ggm..........",
		"..............sstg...g..........",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............otso..............",
		".............oostoo.............",
		"................................",
	],
	"tree_cypress": [
		"................................",
		"................................",
		"................................",
		"..............h.................",
		".............hhhhm..............",
		".............hhllmm.............",
		".............llmmgm.............",
		".............mhlmg..............",
		".............hhhlmm.............",
		".............hh.lmm.............",
		".............lllggm.............",
		".............mhl.mm.............",
		".............hlhlgm.............",
		"............ghhhm.mm............",
		"............mlllmggm............",
		".............ghlmmm.............",
		".............hhhlmm.............",
		".............hhmmmm.............",
		".............lllmgm.............",
		".............mhgggm.............",
		".............hhhlm..............",
		".............lhmlmm.............",
		".............lhmmgm.............",
		".............mmggg..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............otso..............",
		".............oostoo.............",
		"................................",
	],
	"tree_maple": [
		"................................",
		"................................",
		"................................",
		"..............mmmmm.............",
		"............mlhhlhm.............",
		"...........mhhhhllmmg...........",
		"........m.lmllhhllmm.mmm........",
		".......lhhhmmhl.ggmmmllmm.......",
		"......hlmhhmmmllggmmm.hlmm......",
		"......hhlmmlmmmm.mmmhlhhlmm.....",
		".....llllmmgmmlllgmmhl.llmm.....",
		".....m.lggmhlmmhl.hhlmllggm.....",
		".....mmgggmh.lmmmhhhlmm.ggm.....",
		"........mlllllmmmlhlllmmg.......",
		"........gllhggmmmlllggmm........",
		".........mmmgggmmmmmggmm........",
		".........gmmmmmmmmmmgmm.........",
		"............mmmgmmmm............",
		"...............mm...............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............stss..............",
		"..............ssts..............",
		"..............stts..............",
		"..............otso..............",
		".............oostoo.............",
		"................................",
	],
	"rock_jagged": [
		"................",
		"......oo........",
		".....ohhoo......",
		"....ohhmmho.....",
		"...oohhmmmmho...",
		"...ohhmmssmho...",
		"..ohhhmssssmho..",
		"..ohmmsssssmmo..",
		".ohmmsssssssso..",
		".ommssssssssso..",
		"..ogsssssssoo...",
		"...oossssooo....",
		".....ooooo......",
		"................",
		"................",
		"................",
	],
	"grass_wild": [
		"..h.l.h.",
		".h.l.h.l",
		".lhdhlh.",
		"hldcd.lh",
		".dcccdd.",
		"..ccc...",
		"...c....",
		"........",
	],
	"flower_patch": [
		".p.y.p..",
		"..pwp.y.",
		".y.p.y..",
		"..d.p...",
		".dcd.d..",
		"..c.c...",
		"...c....",
		"........",
	],
	"lava_chunk": [
		"................",
		"......oooo......",
		"....oohhhhoo....",
		"...ohmmwwmmho...",
		"...ohmgwwgmho...",
		"...osmmmmmmso...",
		"....osssssso....",
		".....oooooo.....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"ice_crystal": [
		"................",
		".......g........",
		"......ghg.......",
		".....ghhhg......",
		"....ghwhmwhg....",
		"...ghhmmmhhg....",
		"...osssssso.....",
		"....oooooo......",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"crate_box": [
		"................",
		"...oooooooooo...",
		"..ohhhhhhhhho...",
		"..owgggggggwo...",
		"..ohhhhhhhhho...",
		"..ommmmmmmmmo...",
		"..ohhhhhhhhho...",
		"..ossssssssso...",
		"...oooooooooo...",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"barrel_keg": [
		"................",
		".....oooooo.....",
		"....ohhhhhho....",
		"....owmmmmwo....",
		"....ohghhgho....",
		"....owmmmmwo....",
		"....osssssso....",
		".....oooooo.....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"bollard": [
		"................",
		"......llll......",
		".....lhhhhl.....",
		".....lmhwhl.....",
		".....lhhhhl.....",
		"......wwww......",
		"......smmms.....",
		"......smmms.....",
		"......shhhs.....",
		"......smmms.....",
		"......smmms.....",
		"......oooo......",
		"................",
		"................",
		"................",
		"................",
	],
	"vent_cap": [
		"................",
		"...oooooooooo...",
		"..ohggggggggho..",
		"..oghhhhhhhhgo..",
		"..ohgwwwwwwgho..",
		"..oghhhhhhhhgo..",
		"..ohggggggggho..",
		"...oooooooooo...",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"rock_small": [
		"................",
		"................",
		"....oooooooo....",
		"...ohhhhhhho....",
		"...ommmmmmmo....",
		"...ohhhhhhho....",
		"...ommmmmmmo....",
		"...ogsssssgo....",
		"....oooooooo....",
		"....o....o......",
		"....o....o......",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"rock_large": [
		"................",
		"...oooooooooo...",
		"..ohhhhhhhhho...",
		"..ommmmmmmmmo...",
		"..ohhhggghhho...",
		"..ommmmmmmmmo...",
		"..ossssssssso...",
		"..ossssssssso...",
		"...oooooooooo...",
		"...o........o...",
		"...o........o...",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"shop_stand": [
		"......................tlt.......................",
		"..............ooooooootttoooooooo...............",
		"..............offfffffffffffffffo...............",
		"..............ofttttttffsffsffffo...............",
		"..............oftkttktfffsmfffffo......ttttttt..",
		"..............ofttktttfffssfffffo......ttttttt..",
		"..............ofttttttffsffsffffo......tttwttt..",
		"..............ooooooooooooooooooo......ttwtwtt..",
		".....s.ooooooooooooooooooooooooooooooo.tttwttt..",
		"....eeeorrrrrrrrrrrrrrrrrrrrrrrrrrrrro.ttttttt..",
		"....eyeortttttttttttttttttttttttttttro...s......",
		"....eaeorrrrrrrrrrrrrrrrrrrrrrrrrrrrro...s......",
		"....eeeortttttttttttttttttttttttttttro...s......",
		".......orrrrrrrrrrrrrrrrrrrrrrrrrrrrro...sm.....",
		".......ooooooooooooooooooooooooooooooo...mmmmmm.",
		".........ooooooooooooooooooooooooooo.....mmmmmm.",
		".........occccccccccccccccccccccccco.....mmmmmm.",
		".........occmcccccccccccccccccccccco.....s.mmmm.",
		".........ocbsssssboottlttysbbbsbbbco.....s.mmmm.",
		".........ocbmbbbbboptttttsbbbtttbbco.......mmmm.",
		".........ocbbbbbbbouuuuuuubbbsltbbco.oooooommmm.",
		".........ocbbbbbbbouhhhhhsssusttbbco.oqqqqqmmmm.",
		".........ocbbbbbbbouhkhkhsssssttbbco.oqqqqqqqqo.",
		".........ocbbbbbbbouhhihhubbbtttbbco.oqqqqqqqqo.",
		".........ocbbbbbbbbuuuuuuubbbbbbbbco.oqqqqqqqqo.",
		".........ocbbbbbbbbbsssssbbbbbbbbbco.oqkkkkkkqo.",
		".ooooooo.ocbbbbbbbbbsssssbbbbbbbbbco.oqkkkkkkqo.",
		".occccco.occccccccccssssscccccccccco.oqkeeeekqo.",
		".octttcoooooooooorrrrrrrrrrrooooooooooqkeeaekqo.",
		".octttcoocccccccctttttttttttccccccccooqkeyeekqo.",
		".octftcoocbbbbbbbtttttttttttbbbbbbbcooqkeeeekqo.",
		".octttcoocbbbbbbbtttttttttttbbbbbbbcooqkeeeekqo.",
		".octttcoocbbbbbbbtttttttttttbbbbbbbcooqkeeeekqo.",
		".occcccoocdddddbdddddbdddddbddsddbbcooqkkkkkkqo.",
		".occcccoocdsdsdbdspsdbdtdtdbdtttdbbcooqqqqqqqqo.",
		".occcccoocddsddbdsssdbddtddbdtttdbbcooqqqqqqqqo.",
		".occcccoocdddddcdddddcdddddcdddddcccooqqqqqqqqo.",
		".oooooooooooooooooooooooooooooooooooooooooooooo.",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
	],
	"boulder": [
		"........................",
		"......oooooooooo........",
		".....ohhhhhhhhho........",
		".....ommmmmmmmmo........",
		"...ooohhhhhhhhhoooo.....",
		"..ohhhmmmmmmmmmmhhho....",
		"..ommmhhhhhhhhhhmmmo....",
		"..ohhhmmmmmmmmmmhhho....",
		"..ogggssssssssssgggo....",
		"...oooooooooooooooo.....",
		"....o....o....o.........",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
	],
	"spire": [
		"........................",
		"..........ow............",
		".........omwo...........",
		".........omwo...........",
		"........osmwo...........",
		"........osmwo...........",
		"........osmwo...........",
		".......oosmwo...........",
		".......osmmwo...........",
		".......osmmwo...........",
		".......osmmwo...........",
		"......oosmmwo...........",
		"......osmmmwo...........",
		"......osmmmwo...........",
		"......osmmmwo...........",
		"......ssmmmwo...........",
		"......sssssso...........",
		"......ooooooo...........",
		".......o...o............",
		".......o...o............",
		"........................",
		"........................",
		"........................",
		"........................",
	],
}

## Extra biome tiles/obstacles. Sprite ids become tw_volcano_grass_tile, etc.
## Each world has its own ground language: lava-cracked basalt, packed snow,
## riveted plates, and plank boardwalks — not recolored meadow noise.
const BIOME_TILE_PALETTES := {
	"volcano": {"a": "2a1612", "b": "3d2218", "c": "1a0c08", "d": "e85a2a", "e": "ff7a29"},
	"ice": {"a": "c8dcec", "b": "e4f2fa", "c": "8ab0c8", "d": "ffffff", "e": "b8d4e8"},
	"factory": {"a": "2c3038", "b": "3e4650", "c": "1a1e24", "d": "2bbfbe", "e": "e85a2a"},
	"docks": {"a": "6b4a1a", "b": "8a6230", "c": "3a2a10", "d": "2f8fb0", "e": "c9a227"},
}

const BIOME_VOID_PALETTES := {
	"volcano": {"a": "4a1408", "b": "c43018", "c": "e85a2a", "d": "ff7a29", "e": "ffe14a"},
	"ice": {"a": "0e2438", "b": "1a3a58", "c": "2a5a78", "d": "8ad7ff", "e": "d0e8f6"},
	"factory": {"a": "080a0e", "b": "12141a", "c": "1e2430", "d": "2bbfbe", "e": "e85a2a"},
	"docks": {"a": "0a2030", "b": "123848", "c": "1a5068", "d": "4f8fe0", "e": "dfe6f2"},
}

const BIOME_DECAL_PALETTES := {
	"volcano": {"c": "3a1c14", "d": "e85a2a", "l": "ff7a29", "p": "ffdc4d", "w": "fff3b0", "y": "ff7a29", "h": "ff9a40"},
	"ice": {"c": "9cbcd4", "d": "d0e8f6", "l": "ffffff", "p": "e8f6ff", "w": "ffffff", "y": "b8d4e8", "h": "ffffff"},
	"factory": {"c": "4a4a52", "d": "2bbfbe", "l": "e85a2a", "p": "8b95a1", "w": "dfe6f2", "y": "ffe14a", "h": "2bbfbe"},
	"docks": {"c": "8a6230", "d": "2f8fb0", "l": "c9a227", "p": "dfe6f2", "w": "ffffff", "y": "4f8fe0", "h": "dfe6f2"},
}

const BIOME_ROCK_PALETTES := {
	"volcano": {"o": "1a0808", "s": "3a1410", "m": "c43018", "h": "e85a2a", "g": "ff7a29", "w": "ffe14a"},
	"ice": {"o": "3a5068", "s": "7aa0b8", "m": "b8d4e8", "h": "e8f6ff", "g": "ffffff", "w": "d0e8f6"},
	"factory": {"o": "101418", "s": "3a3a40", "m": "5a6270", "h": "8b95a1", "g": "2bbfbe", "w": "e85a2a"},
	"docks": {"o": "1a1210", "s": "3a2a10", "m": "6b4a1a", "h": "c9a227", "g": "2f8fb0", "w": "dfe6f2"},
}

const BIOME_TREE_PALETTES := {
	"volcano": {"o": "1a0808", "t": "4a2a18", "s": "2a1810", "m": "3a2214", "l": "6b3a20", "h": "c45a20", "g": "e85a2a", "w": "ffe08c"},
	"ice": {"o": "3a5068", "t": "7aa0b8", "s": "5a7088", "m": "8ab0c8", "l": "c8dcec", "h": "e8f6ff", "g": "ffffff", "w": "ffffff"},
	"factory": {"o": "101418", "t": "3a4656", "s": "1a1e24", "m": "5a6270", "l": "8b95a1", "h": "2bbfbe", "g": "e85a2a", "w": "e85a2a"},
	"docks": {"o": "1a1210", "t": "6b4a1a", "s": "3a2a10", "m": "8a6230", "l": "c9a227", "h": "2f8fb0", "g": "dfe6f2", "w": "dfe6f2"},
}

const _VOLCANO_TILE := [
	"bbbabbbbabbbabbb",
	"baaacaaabaaacaaa",
	"bbbabdebbbabdbbb",
	"cbbabbbbbbbabbbc",
	"bbbaabbbbaaabbbb",
	"aaacaaaabaaacaaa",
	"bbbabbbdebbabbbb",
	"bbbbabbbbbbbabbb",
	"baaacaaabaaacaaa",
	"bbbabbbbbdebabbb",
	"cbbabbbbaaaabbbc",
	"bbbaabbbbbbbabbb",
	"aaacaaaabaaacaaa",
	"bbbabdebbbabbbbb",
	"bbbbabbbbbbbabbb",
	"baaacaaabaaacaaa",
]
const _ICE_TILE := [
	"bbbbdbbbbbbbdbbb",
	"bdddbbbbebbbdddb",
	"bbbbbbebbbbbbbbb",
	"bbebbbbdbbbbebbb",
	"bbbbbbbbbbbbdbbb",
	"dbbbbebbbbbbbbbd",
	"bbbbbbbbbbebbbbb",
	"bbdbbbbbbbbbdbbb",
	"bbbbbbebbbbbbbbb",
	"bebbbbbbbbbebbbb",
	"bbbbdbbbbbbbbbdb",
	"bbbbbbbbdbbbbbbb",
	"bbbebbbbbbbbbebb",
	"bbbbbbbbbbebbbbb",
	"dbbbbbbbbbbbbbbd",
	"bbbbdbbbbbbbdbbb",
]
const _FACTORY_FLOOR := [
	"cccccccccccccccc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cbbbbbeeeebbbbbc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cbbbbbeeeebbbbbc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cccccccccccccccc",
]
const _DOCKS_PLANK := [
	"bbbbbbbbbbbbbbbb",
	"acacaeacacacaeac",
	"bbbbbbbbbbbbbbbb",
	"cacacacaeacacaca",
	"bbbbbbbbbbbbbbbb",
	"acaeacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacaeacaca",
	"bbbbbbbbbbbbbbbb",
	"acacacaeacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacaeacacacacaca",
	"bbbbbbbbbbbbbbbb",
	"acacacacacaeacac",
	"bbbbbbbbbbbbbbbb",
	"caeacacacacacaca",
]
const _VOLCANO_VOID := [
	"aaabaaabaaabaaab",
	"abcdeabcdeabcdea",
	"aaabaaabaaabaaab",
	"baaabaaabaaabaaa",
	"cdeabcdeabcdeabc",
	"aaabaaabaaabaaab",
	"abaaabaaabaaabaa",
	"eabcdeabcdeabcde",
	"aaabaaabaaabaaab",
	"aaabaaabaaabaaab",
	"bcdeabcdeabcdeab",
	"aaabaaabaaabaaab",
	"baaabaaabaaabaaa",
	"deabcdeabcdeabcd",
	"aaabaaabaaabaaab",
	"abaaabaaabaaabaa",
]
const _ICE_VOID := [
	"bbbbbbbbbbbbbbbb",
	"baaaaaaaeaaaaaab",
	"baaaaacaaaaaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaaeaaaaaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaadaaaaaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaaaaaaeaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaacaaaaaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaaeaaaaaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaaaaadaaaaab",
	"bbbbbbbbbbbbbbbb",
]
const _FACTORY_VOID := [
	"aaaaaaaaaaaaaaaa",
	"abbbbbbbbbbbbbba",
	"abaaaaaaaaaaaaba",
	"abaaeeaaaaeeaaba",
	"abaaaaaaaaaaaaba",
	"abaaddddddddaaba",
	"abaaaaaaaaaaaaba",
	"abaaaaaaaaaaaaba",
	"abaaaaaaaaaaaaba",
	"abaaddddddddaaba",
	"abaaaaaaaaaaaaba",
	"abaaeeaaaaeeaaba",
	"abaaaaaaaaaaaaba",
	"abbbbbbbbbbbbbba",
	"aaaaaaaaaaaaaaaa",
	"aaaaaaaaaaaaaaaa",
]
const _DOCKS_VOID := [
	"bbbbbbbbbbbbbbbb",
	"bcccbcccbcccbccc",
	"bbbbbbbbbbbbbbbb",
	"cccbcccbcccbcccb",
	"bbbbbebbbbbebbbb",
	"bcccbcccbcccbccc",
	"bbbbbbbbbbbbbbbb",
	"cccbcccbcccbcccb",
	"bbbbbbbbbbbbbbbb",
	"bcccbcccdcccbccc",
	"bbbbbbbbbbbbbbbb",
	"cccbcccbcccbcccb",
	"bbbebbbbbbbbbebb",
	"bcccbcccbcccbccc",
	"bbbbbbbbbbbbbbbb",
	"cccbcccbcccbcccb",
]
const _VOLCANO_TUFT := [
	"........",
	"...y....",
	"..yly...",
	"...l....",
	"...d....",
	"..dcd...",
	"...c....",
	"........",
]
const _ICE_TUFT := [
	"........",
	"..w.w...",
	".wwwww..",
	"..www...",
	"...d....",
	"..dcd...",
	"...c....",
	"........",
]
const _FACTORY_TUFT := [
	"........",
	"...yy...",
	"...dd...",
	"..dwwd..",
	"...dd...",
	"...pp...",
	"...c....",
	"........",
]
const _DOCKS_TUFT := [
	"........",
	"........",
	"..l..l..",
	"...ll...",
	"..dddd..",
	"...dd...",
	"...c....",
	"........",
]
const _VOLCANO_ROCK := [
	"................",
	"......oooo......",
	"....oohhhhoo....",
	"...ohmmmmmmho...",
	"...ohmgwwgmho...",
	"...osmmmmmmso...",
	"....osssssso....",
	".....oooooo.....",
	".....o....o.....",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
]
const _ICE_ROCK := [
	"................",
	".......g........",
	"......ghg.......",
	".....ghhhg......",
	"....ghwmwhg.....",
	"...ghmmmmmhg....",
	"...osssssso.....",
	"....oooooo......",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
]
const _FACTORY_CRATE := [
	"................",
	"...oooooooooo...",
	"..ohhhhhhhhho...",
	"..owgggggggwo...",
	"..ohhhhhhhhho...",
	"..ommmmmmmmmo...",
	"..ohhhhhhhhho...",
	"..ossssssssso...",
	"...oooooooooo...",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
]
const _DOCKS_BARREL := [
	"................",
	".....oooooo.....",
	"....ohhhhhho....",
	"....owmmmmwo....",
	"....ohghhgho....",
	"....owmmmmwo....",
	"....osssssso....",
	".....oooooo.....",
	".....o....o.....",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
]
const _VOLCANO_TREE := [
	"................................",
	"................................",
	"...............mm...............",
	".............lhhhm..............",
	"............mhhhllmg............",
	".........mhllmgllhh.lm..........",
	"........mlhhhlhmglhhlmm.........",
	"........m.llllhhlmml.lmm........",
	"........hlgmhhl.whmmmlmm........",
	".......lhh.lhmllggmmmhlmmm......",
	"......mlllllwhmmggggmllmmmm.....",
	".....mgmlhg.llgmmgggmlggmmm.....",
	".....mhhmmgmgmggm.mmwhhgmhm.....",
	".....lhhlmmm.mmmgggmmhhhlmm.....",
	".....hl.lmmmmgwhggmmmllllmm.....",
	".....mllggmhmmmmmmmglmhlggm.....",
	".....mmmggmllmgmmmmggmmmggm.....",
	".......mmgmmmggmmmmggmmmm.......",
	"..........mmmmmgmmmmmm..........",
	"................................",
	"..............stss..............",
	"..............ssts..............",
	".............hstts..............",
	"..............stss..............",
	"..............sstsw.............",
	"..............stts..............",
	"..............stss..............",
	"..............ssts..............",
	"..............stts..............",
	"..............otso..............",
	".............oostoo.............",
	"................................",
]
const _ICE_TREE := [
	"................................",
	"................................",
	"...............hwh..............",
	".............wwwwwww............",
	"...............wg...............",
	"..............lmmlw.............",
	"..............wwwh..............",
	".............wlwmlww............",
	"............wlwlglwmw...........",
	".............wllmmlw............",
	".............llmmlll............",
	"............lmllmlmll...........",
	"...........llllmwhlll...........",
	"..........llllmwmwhmlll.........",
	".........lllmlllmmllllml........",
	".............llmmllll...........",
	"............lmlmgmmlll..........",
	"...........mlllgmmlllm..........",
	"..........llllmmmmlmllll........",
	".........lllmllmmgllllmll.......",
	"........llmlllmmgmmlmllll.......",
	".......lmllllmsstsmllllmlll.....",
	"..............stts..............",
	"..............stss..............",
	"..............ssts..............",
	"..............stts..............",
	"..............stss..............",
	"..............ssts..............",
	"..............stts..............",
	"..............otso..............",
	".............oostoo.............",
	"................................",
]
const _FACTORY_TREE := [
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"...........w.h.....w.h..........",
	"............w.......w...........",
	".........lllllll.lllllll........",
	".........hhhhhhh.hhhhhhh........",
	"..........smmms...smmms.........",
	"..........smmms...smmms.........",
	"..........smmms...smmms.........",
	"..........shhhs...shhhs.........",
	"..........smmms...smmms.........",
	"..........smmms...smmms.........",
	"..........smmms...smmms.........",
	"..........shhhs...shhhs.........",
	"..........smmms...smmms.........",
	"..........smmms...smmms.........",
	"..........smmms...smmms.........",
	"..........shhhs...shhhs.........",
	"..........smmms...smmms.........",
	"..........smmms...smmms.........",
	"..........smmms...smmms.........",
	"..........shhhs...shhhs.........",
	"..........smmms...smmms.........",
	"..........smmms...smmms.........",
	"..........smmms...smmms.........",
	"........ooooooooooooooooo.......",
	"........ooooooooooooooooo.......",
	"................................",
	"................................",
]
const _DOCKS_TREE := [
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	".............ststts.............",
	".............ssttss.............",
	"............hhhhhhhh............",
	"............llllllll............",
	"............llllllll............",
	"............llllllll............",
	".............ststts.............",
	".............ssttss.............",
	".............sttsts.............",
	".............ststts.............",
	"............wwwwwwww............",
	"............mmmmmmmm............",
	".............ststts.............",
	".............ssttss.............",
	".............sttsts.............",
	".............ststts.............",
	"............wssttss.............",
	".............sttsts.............",
	".............ststtsl............",
	".............ssttss.............",
	".............sttsts.............",
	".............ststts.............",
	"...........h.ssttss.............",
	".............ottsto.w...........",
	"............ootsttoo............",
	"................................",
]
const _VOLCANO_LUSH := [
	"cbbacbbacbbacbba",
	"baaacaaabaaacaaa",
	"cbbabdeccbabdbba",
	"cbbabbbbbbbabbbc",
	"cbbaabbbcaaabbbb",
	"aaacaaaabaaacaaa",
	"cbbabbbdebbabbbc",
	"cbbbabbbbbbbabbc",
	"baaacaaabaaacaaa",
	"cbbabbbbbdebabbc",
	"cbbabbbbaaaabbbc",
	"cbbaabbbbbbbabbc",
	"aaacaaaabaaacaaa",
	"cbbabdeccbabbbbc",
	"cbbbabbbbbbbabbc",
	"baaacaaabaaacaaa",
]
const _ICE_LUSH := [
	"cbbbdbbbcbbbdbbb",
	"bdddbbbbebbbdddb",
	"cbbbbbebbbbbbbbc",
	"bbebbbbdbbbbebbb",
	"cbbbbbbbbbbbdbbc",
	"dbbbbebbbbbbbbbd",
	"cbbbbbbbbbebbbbc",
	"bbdbbbcbbbbbdbbb",
	"cbbbbbebbbbbbbbc",
	"bebbbbbbbbbebbbb",
	"cbbbdbbbbbbbbbdc",
	"cbbbbbbbdbbbbbbc",
	"bbbebbcbbbbbbebb",
	"cbbbbbbbbbebbbbc",
	"dbbbcbbbbbbbbbbd",
	"cbbbdbbbcbbbdbbb",
]
const _FACTORY_LUSH := [
	"cccccccccccccccc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cbbbbbeeeebbbbbc",
	"cbccccccccccccbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbccccccccccccbc",
	"cbbbbbeeeebbbbbc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cccccccccccccccc",
]
const _DOCKS_LUSH := [
	"cccccccccccccccc",
	"acacaeacacacaeac",
	"bbbbbbbbbbbbbbbb",
	"cacacacaeacacaca",
	"cccccccccccccccc",
	"acaeacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacaeacaca",
	"cccccccccccccccc",
	"acacacaeacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacaeacacacacaca",
	"cccccccccccccccc",
	"acacacacacaeacac",
	"bbbbbbbbbbbbbbbb",
	"caeacacacacacaca",
]
const _VOLCANO_MEADOW := [
	"bbbabdebbbabdbbb",
	"baaacaaabaaacaaa",
	"bbdebbbbbbdebbbb",
	"cbbabbbbbbbabbbc",
	"bbbaabdebaaabbbb",
	"aaacaaaabaaacaaa",
	"bbbabbbdebbabbbb",
	"bbbbabdebbbbabbb",
	"baaacaaabaaacaaa",
	"bbbabbbbbdebabbb",
	"cbbabbbbaaaabbbc",
	"bbbaabdebbbbabbb",
	"aaacaaaabaaacaaa",
	"bbbabdebbbabbbbb",
	"bbbbabbbbbbbabbb",
	"baaacaaabaaacaaa",
]
const _ICE_MEADOW := [
	"bbbbdbbbebbbdbbb",
	"bdddbbbbebbbdddb",
	"bbbbbbebbbbbebbb",
	"bbebbbbdbbbbebbb",
	"bbbbbbebbbbbdbbb",
	"dbbbbebbbbbebbbd",
	"bbbbbbbbbbebbbbb",
	"bbdbbbbbbbbbdbbb",
	"bbbbbbebbbbbebbb",
	"bebbbbdbbbbebbbb",
	"bbbbdbbbbbbbbbdb",
	"bbbbbbebdbbbbbbb",
	"bbbebbbbbbbbbebb",
	"bbbbdbbbbbebbbbb",
	"dbbbbbbebbbbbbbd",
	"bbbbdbbbbbbbdbbb",
]
const _FACTORY_MEADOW := [
	"cccccccccccccccc",
	"ceeeeeeeeeeeeeec",
	"cebbbbbbbbbbbbec",
	"cebbddddddddbbec",
	"cebbbbbbbbbbbbec",
	"ceeeeeeeeeeeeeec",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"ceeeeeeeeeeeeeec",
	"cebbbbbbbbbbbbec",
	"cebbddddddddbbec",
	"cebbbbbbbbbbbbec",
	"ceeeeeeeeeeeeeec",
	"cbbbbbbbbbbbbbbc",
	"cccccccccccccccc",
]
const _DOCKS_MEADOW := [
	"bbbbbbbbbbbbbbbb",
	"aeaeaeaeaeaeaeae",
	"bbbbbbbbbbbbbbbb",
	"eaeaeaeaeaeaeaea",
	"bbbbbbbbbbbbbbbb",
	"aeaeaeaeaeaeaeae",
	"bbbbbbbbbbbbbbbb",
	"eaeaeaeaeaeaeaea",
	"bbbbbbbbbbbbbbbb",
	"aeaeaeaeaeaeaeae",
	"bbbbbbbbbbbbbbbb",
	"eaeaeaeaeaeaeaea",
	"bbbbbbbbbbbbbbbb",
	"aeaeaeaeaeaeaeae",
	"bbbbbbbbbbbbbbbb",
	"eaeaeaeaeaeaeaea",
]
const _VOLCANO_DIRT := [
	"ccccccccccccccca",
	"caaaaaaacaaaaaac",
	"caaccccaacccccac",
	"caaaaaaacaaaaaac",
	"ccccccccccccccca",
	"caaaaaaacaaaaaac",
	"caaccccaacccccac",
	"caaaaaaacaaaaaac",
	"ccccccccccccccca",
	"caaaaaaacaaaaaac",
	"caaccccaacccccac",
	"caaaaaaacaaaaaac",
	"ccccccccccccccca",
	"caaaaaaacaaaaaac",
	"caaccccaacccccac",
	"ccccccccccccccca",
]
const _ICE_DIRT := [
	"cccccccccccccccc",
	"caaaaaeaaaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaaaadaaaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaaaaeaaaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaaaacaaaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaaaaeaaaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaaaadaaaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaaaaeaaaaaaaac",
	"caaaaaaaaaaaaaac",
	"cccccccccccccccc",
]
const _FACTORY_DIRT := [
	"aaaaaaaaaaaaaaaa",
	"abbbbbbbbbbbbbba",
	"abaaaaaaaaaaaaba",
	"abaaccccccccaaba",
	"abaaaaaaaaaaaaba",
	"abbbbbbbbbbbbbba",
	"aaaaaaaaaaaaaaaa",
	"abbbbbbbbbbbbbba",
	"abaaaaaaaaaaaaba",
	"abaaccccccccaaba",
	"abaaaaaaaaaaaaba",
	"abbbbbbbbbbbbbba",
	"aaaaaaaaaaaaaaaa",
	"abbbbbbbbbbbbbba",
	"abaaaaaaaaaaaaba",
	"aaaaaaaaaaaaaaaa",
]
const _DOCKS_DIRT := [
	"cccccccccccccccc",
	"caaaaaaaeaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaacaaaaaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaaaaaaeaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaacaaaaaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaaaaaaeaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaacaaaaaaaaaac",
	"caaaaaaaaaaaaaac",
	"caaaaaaaeaaaaaac",
	"caaaaaaaaaaaaaac",
	"cccccccccccccccc",
]


## Town building rows + palettes (docks biome). Baked as plain town_*.png by
## tools/generate_town.py and placed directly by the arena; these rows exist so the
## forge can also bake tw_docks_town_* variants. Muted earth tones, 1-2px outlines.
const _TOWN_HOUSE_PALETTE := {
	"o": "201812", "w": "8a6a48", "s": "6e5338", "r": "5a3a26", "R": "462c1c",
	"d": "3a2a1c", "l": "d8c9a0", "g": "2a2620", "t": "4a3420", "h": "3a4a2a",
}
const _TOWN_HOUSE_ROWS := [
	"................................",
	"................................",
	"................oo..............",
	"..............oorroo............",
	"............oorrrroo............",
	"..........oRRrrrrrooo...........",
	".........oRRrrrrrrroo...........",
	"........oRRrrrrrrrrroo..........",
	".......oRRrrrrrrrrrrroo.........",
	"......oRRRRrrrrrrrrRRoo.........",
	".......ooooooooooooooooo........",
	".......owwwwwwwwwwwwwwo.........",
	".......owwwowwwoowwwwo..........",
	".......owwwolwwlwwolwwwo........",
	".......owwwolwwlwwolwwwo........",
	".......owwwolwwlwwolwwwo........",
	".......ooooooooooooooooo........",
	".......owwwwwwwwwwwwwwo.........",
	".......owwwwwdwwwwdwwwo.........",
	".......owwwwwdwwwwdwwwo.........",
	".......owwwwwddddwwwwwo.........",
	".......owwwwwdwwwwdwwwo.........",
	".......owwwwwdwwwwdwwwo.........",
	".......ooooooooooooooooo........",
	"......ottttttttttttttttto.......",
	".....ohhhtttttttttttthho........",
	"......ohhhtttttttthhho..........",
	".......ohhtttttthhho............",
	".......oohhtthhoo...............",
	"........ooooooo.................",
	"................................",
	"................................",
]
const _TOWN_SHOP_PALETTE := {
	"o": "1a1410", "w": "9a7a54", "s": "7a5e3e", "a": "c43018", "A": "8a2414",
	"r": "5a3a26", "R": "462c1c", "d": "3a2a1c", "l": "d8c9a0", "g": "2a2620",
	"t": "4a3420", "T": "3a2a1a", "e": "c9a227",
}
const _TOWN_SHOP_ROWS := [
	"....................................",
	"....................................",
	"....................................",
	"...............ooo..................",
	".............oorrooo................",
	"...........oRRrrrrroo...............",
	".........oRRrrrrrrrrroo.............",
	"........oRRrrrrrrrrRRRoo............",
	".......oooooooooooooooooo...........",
	".......owwwwwwwwwwwwwwwwo...........",
	".......owwwwwwwwwwwwwwwwo...........",
	".......owaawaawaawaawaao............",
	".......owAaAaAaAaAaAaAao............",
	".......owwwwwwwwwwwwwwwwo...........",
	".......owlwwglwwlwwglwwwo...........",
	".......owlwwglwwlwwglwwwo...........",
	".......owlwwglwwlwwglwwwo...........",
	".......oooooooooooooooooo...........",
	".......owwwwwwwwwwowwwwwwwo.........",
	".......owwwwwwwwwodwwwwwwwwo........",
	".......owwwwwwwwwodwwwwwwwwo........",
	".......owwwwwwdwwodwwwwwwwwo........",
	".......owwwwwwdwwodwwwwwwwwo........",
	".......owwwwwwddddwwwwwwwwwwo.......",
	".......owwwwwwddddwwwwwwwwwwo.......",
	".......owwwwwwwwwwwwwwwwwwwwo.......",
	"......ottttttttttttttttttttto.......",
	".....oTTTTTTTTTTTTTTTTTTTTTTTo......",
	".....oTttttttttttttttttttttTTo......",
	"......oTTTTTTTTTTTTTTTTTTTTTo.......",
	".......oooooooooooooooooooo.........",
	"....................................",
	"....................................",
	"....................................",
	"....................................",
	"....................................",
]
const _TOWN_CHURCH_PALETTE := {
	"o": "1c1a18", "w": "b8a88c", "s": "93846a", "r": "4a4a52", "R": "383840",
	"t": "5a4a3a", "l": "d8d2c0", "g": "2a2620", "c": "d8c88c", "d": "3a2a1c",
	"h": "3a4a2a",
}
const _TOWN_CHURCH_ROWS := [
	"........................................",
	"........................................",
	"................cc......................",
	"................cc......................",
	"..............ccccc.....................",
	"................cc......................",
	"................cc......................",
	"............ooooooooo...................",
	"............orrRRroo....................",
	"..........oRRrrrrrrRoo..................",
	"........oRRrrrrrrrrRoo..................",
	".......oooooooooooooo...................",
	".......owwlllwwwwwwwwo..................",
	".......owwlllwwwwwwwwo..................",
	".......owwwwwwwwwwwwwo..................",
	".......owwwwwwwwwwwwwo..................",
	"......owwwwwwowwwwowwwwo................",
	"......owwwwwolwwolwwwwwo................",
	"......owwwwwolwwolwwwwwo................",
	"......owwwwwolwwolwwwwwo................",
	".......owwwwwwwwwwwwwo..................",
	".......owwwwwwwwwwwwwo..................",
	".......owwwwwwwwwwwwwo..................",
	".......owwwwwwwwwwwwwo..................",
	".......owwwwwwwwwwwwwo..................",
	".......owwwwwwwwwwwwwo..................",
	".......owwwwddwwwwwwwo..................",
	".......owwwwddwwwwwwwo..................",
	".......owwwwddddwwwwwo..................",
	".......owwwwddddwwwwwo..................",
	".......owwwwwwwwwwwwwo..................",
	".......owwwwwwwwwwwwwo..................",
	".......oooooooooooooo...................",
	"......ohhhhhhhhhhhhhho..................",
	".....ohhhhhhhhhhhhhhhho.................",
	"......ohhhhhhhhhhhhhho..................",
	".......oohhhhhhhhhoo....................",
	"........ooooooooooo.....................",
	"........................................",
	"........................................",
]
const _TOWN_WELL_PALETTE := {
	"o": "1a1610", "w": "8a7a64", "s": "6a5c48", "W": "a89878", "r": "4a3a28",
	"R": "3a2c1c", "l": "2a3440", "L": "3a4a58", "b": "5a3a20", "B": "3a2414",
}
const _TOWN_WELL_ROWS := [
	"............................",
	"............................",
	"............rrrrrr..........",
	"...........rrRRRRrr.........",
	"..........rRRRRRRRRr........",
	"........ooooooooooooo.......",
	".......owWwwwwwWWWWwo.......",
	"......owWWwwwwwWwwwwwo......",
	"......oWWwwllllllwwWo.......",
	"......owwwlLlllllllwwwo.....",
	"......owwwlLlllllllwwwo.....",
	"......owwwlllllllllwwwo.....",
	"......owwwwwllllwwwwwo......",
	".......owwwwwwwwwwwwwo......",
	".......ossssssssssssswo.....",
	"......ossoWWWWWWWWWWso......",
	"......osWWwwwwwwwwwwso......",
	"......oswwwsswwwwsswwso.....",
	"......osswWWWWWWWWWWsso.....",
	"......ossoWWWWWWWWWWso......",
	".......ossssssssssssswo.....",
	"........ooooooooooooo.......",
	"............bbbb............",
	"...........bBBBb............",
	"...........BBBBb............",
	"...........bBBBb............",
	"............................",
	"............................",
]

static func all_sprites() -> Dictionary:
	var sprites: Dictionary = {}
	_collect(sprites, ENEMY_ROWS, ENEMY_PALETTES)
	_collect(sprites, BOSS_ROWS, BOSS_PALETTES)
	_collect(sprites, PROP_ROWS, PROP_PALETTES)
	_collect(sprites, TERRAIN_ROWS, TERRAIN_PALETTES)
	var tiles := {
		"volcano": _VOLCANO_TILE,
		"ice": _ICE_TILE,
		"factory": _FACTORY_FLOOR,
		"docks": _DOCKS_PLANK,
	}
	var voids := {
		"volcano": _VOLCANO_VOID,
		"ice": _ICE_VOID,
		"factory": _FACTORY_VOID,
		"docks": _DOCKS_VOID,
	}
	var tufts := {
		"volcano": _VOLCANO_TUFT,
		"ice": _ICE_TUFT,
		"factory": _FACTORY_TUFT,
		"docks": _DOCKS_TUFT,
	}
	var rocks := {
		"volcano": _VOLCANO_ROCK,
		"ice": _ICE_ROCK,
		"factory": _FACTORY_CRATE,
		"docks": _DOCKS_BARREL,
	}
	var trees := {
		"volcano": _VOLCANO_TREE,
		"ice": _ICE_TREE,
		"factory": _FACTORY_TREE,
		"docks": _DOCKS_TREE,
	}
	var lush := {
		"volcano": _VOLCANO_LUSH,
		"ice": _ICE_LUSH,
		"factory": _FACTORY_LUSH,
		"docks": _DOCKS_LUSH,
	}
	var meadows := {
		"volcano": _VOLCANO_MEADOW,
		"ice": _ICE_MEADOW,
		"factory": _FACTORY_MEADOW,
		"docks": _DOCKS_MEADOW,
	}
	var dirts := {
		"volcano": _VOLCANO_DIRT,
		"ice": _ICE_DIRT,
		"factory": _FACTORY_DIRT,
		"docks": _DOCKS_DIRT,
	}
	for biome in BIOME_TILE_PALETTES.keys():
		sprites["%s_grass_tile" % biome] = {"rows": tiles[biome], "palette": _tone_ground(BIOME_TILE_PALETTES[biome])}
		sprites["%s_void_tile" % biome] = {"rows": voids[biome], "palette": _tone_ground(BIOME_VOID_PALETTES[biome])}
		sprites["%s_grass_tuft" % biome] = {"rows": tufts[biome], "palette": _tone_terrain(BIOME_DECAL_PALETTES[biome])}
		sprites["%s_grass_long" % biome] = {"rows": TERRAIN_ROWS.grass_long, "palette": _tone_terrain(BIOME_DECAL_PALETTES[biome])}
		sprites["%s_grass_flower" % biome] = {"rows": TERRAIN_ROWS.grass_flower, "palette": _tone_terrain(BIOME_DECAL_PALETTES[biome])}
		sprites["%s_grass_bloom" % biome] = {"rows": TERRAIN_ROWS.grass_bloom, "palette": _tone_terrain(BIOME_DECAL_PALETTES[biome])}
		sprites["%s_grass_wild" % biome] = {"rows": TERRAIN_ROWS.grass_wild, "palette": _tone_terrain(BIOME_DECAL_PALETTES[biome])}
		sprites["%s_flower_patch" % biome] = {"rows": TERRAIN_ROWS.flower_patch, "palette": _tone_terrain(BIOME_DECAL_PALETTES[biome])}
		sprites["%s_grass_lush" % biome] = {"rows": lush[biome], "palette": _tone_ground(BIOME_TILE_PALETTES[biome])}
		sprites["%s_grass_meadow" % biome] = {"rows": meadows[biome], "palette": _tone_ground(BIOME_TILE_PALETTES[biome])}
		sprites["%s_dirt_tile" % biome] = {"rows": dirts[biome], "palette": _tone_ground(BIOME_TILE_PALETTES[biome])}
		sprites["%s_lava_chunk" % biome] = {"rows": TERRAIN_ROWS.lava_chunk, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_ice_crystal" % biome] = {"rows": TERRAIN_ROWS.ice_crystal, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_crate_box" % biome] = {"rows": TERRAIN_ROWS.crate_box, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_barrel_keg" % biome] = {"rows": TERRAIN_ROWS.barrel_keg, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_bollard" % biome] = {"rows": TERRAIN_ROWS.bollard, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_vent_cap" % biome] = {"rows": TERRAIN_ROWS.vent_cap, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_tree_oak" % biome] = {"rows": trees[biome], "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_tree_pine" % biome] = {"rows": TERRAIN_ROWS.tree_pine if biome != "ice" else _ICE_TREE, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_tree_dead" % biome] = {"rows": TERRAIN_ROWS.tree_dead, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_tree_pipe" % biome] = {"rows": TERRAIN_ROWS.tree_pipe if biome != "factory" else _FACTORY_TREE, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_tree_piling" % biome] = {"rows": TERRAIN_ROWS.tree_piling if biome != "docks" else _DOCKS_TREE, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_tree_willow" % biome] = {"rows": TERRAIN_ROWS.tree_willow, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_tree_round" % biome] = {"rows": TERRAIN_ROWS.tree_round, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_tree_fir" % biome] = {"rows": TERRAIN_ROWS.tree_fir, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_tree_palm" % biome] = {"rows": TERRAIN_ROWS.tree_palm, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_tree_cypress" % biome] = {"rows": TERRAIN_ROWS.tree_cypress, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_tree_maple" % biome] = {"rows": TERRAIN_ROWS.tree_maple, "palette": _tone_terrain(BIOME_TREE_PALETTES[biome])}
		sprites["%s_rock_small" % biome] = {"rows": rocks[biome], "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_rock_large" % biome] = {"rows": TERRAIN_ROWS.rock_large, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_rock_jagged" % biome] = {"rows": TERRAIN_ROWS.rock_jagged, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_boulder" % biome] = {"rows": TERRAIN_ROWS.boulder, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_spire" % biome] = {"rows": TERRAIN_ROWS.spire, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
	# Town buildings: shared across all biomes (not biome-toned). These are baked
	# pixel-art PNGs in assets/sprites/ (see tools/generate_town.py) — they are NOT
	# rows/palette here; this just registers the sprite ids so the forge bakes the
	# tw_<biome>_town_* variants if desired. The arena places the base town_*.png
	# directly for the docks biome.
		if biome == "docks":
			sprites["town_house"] = {"rows": _TOWN_HOUSE_ROWS, "palette": _TOWN_HOUSE_PALETTE}
			sprites["town_shop"] = {"rows": _TOWN_SHOP_ROWS, "palette": _TOWN_SHOP_PALETTE}
			sprites["town_church"] = {"rows": _TOWN_CHURCH_ROWS, "palette": _TOWN_CHURCH_PALETTE}
			sprites["town_well"] = {"rows": _TOWN_WELL_ROWS, "palette": _TOWN_WELL_PALETTE}
	return sprites


## Desaturate + lighten a biome terrain palette toward the old grass-meadow tone.
## Pure palette transform — no sprite/rows touched. TERRAIN_SAT_ADJUST is the knob.
## Public so the forge can route the untoned classic terrain through the same path.
static func tone_terrain_palette(palette: Dictionary, sat_scale: float = TERRAIN_SAT_ADJUST) -> Dictionary:
	var tweaked: Dictionary = {}
	for key in palette:
		var color := Color(str(palette[key]))
		var gray := color.get_luminance()
		color.s = clampf(color.s * sat_scale, 0.0, 1.0)
		color.v = clampf(lerpf(color.v, gray, TERRAIN_LIGHT_ADJUST), 0.0, 1.0)
		tweaked[key] = color.to_html(false)
	return tweaked


static func _tone_terrain(palette: Dictionary) -> Dictionary:
	return tone_terrain_palette(palette)


static func _tone_ground(palette: Dictionary) -> Dictionary:
	return tone_terrain_palette(palette, GROUND_SAT_ADJUST)


static func _collect(sprites: Dictionary, rows_by_name: Dictionary, palettes: Dictionary) -> void:
	for sprite_name in rows_by_name:
		sprites[sprite_name] = {
			"rows": rows_by_name[sprite_name],
			"palette": palettes[sprite_name],
		}
