class_name ToborBiomeEnemies
extends RefCounted

## Hand-authored 16×16 (24×24 bosses) silhouettes per later biome.
## Inspired by — not copied from — Kenmi volcano enemies, VEXED magma/ice
## dungeon packs, Maru factory robots, and PixyMoon/SakPix harbor crabs.

const VOLCANO := {
	"o": "2a0808", "f": "e85a2a", "l": "ffe08c", "e": "181410",
	"w": "f2f4f0", "g": "e82e26", "s": "5a2010", "h": "ff9a3a",
}
const ICE := {
	"o": "163048", "f": "d8f0ff", "l": "ffffff", "e": "0a2038",
	"w": "e8f8ff", "g": "5ec8ff", "s": "4a7898", "h": "a8d0e8", "m": "c9a878",
}
const DOCKS := {
	"o": "1a1210", "f": "c45a20", "l": "ffe08c", "e": "181410",
	"w": "f2f4f0", "g": "2bbfbe", "s": "6b4a1a", "h": "e85a2a",
	"m": "8b95a1", "n": "4f8fe0",
}

const VOLCANO_ROWS := {
	"grunt": [
		"................",
		".....ssssss.....",
		"....sfffffs.....",
		"...sffhhhffs....",
		"..sffgggggffs...",
		"..sfhfeefhffs...",
		"..sfhhhhhhhfs...",
		"..sfffffffffss..",
		"...sflffffls....",
		"....ssffffss....",
		".....s.ss.s.....",
		"....g......g....",
		"...gg......gg...",
		"................",
		"................",
		"................",
	],
	"swarmling": [
		".g...g....g...g.",
		"..g.ssssssss.g..",
		".gs.shhhhhs.sg..",
		"..s.sheeehs.s...",
		".gs.shhhhhs.sg..",
		"..s.shlllhs.s...",
		".g.s.shhhs.s.g..",
		"g.s...ssss...s.g",
		".g.s.s....s.s.g.",
		"..g.s......s.g..",
		".g.g........g.g.",
		"..g..........g..",
		"................",
		"................",
		"................",
		"................",
	],
	"spitter": [
		"......oooo......",
		".....owwwwo.....",
		"....oweeeewo....",
		"....owwwwwwo....",
		".....owwwwo.....",
		"......osso......",
		".....sffffs.....",
		"....sffhhffs....",
		"...sfgggggfs....",
		"...sfffffffss...",
		"....ssssssss....",
		".....g....g.....",
		"................",
		"................",
		"................",
		"................",
	],
	"drifter": [
		"g..............g",
		".g....oooo....g.",
		"g....owwwwo....g",
		"....oweewwo.....",
		"....owwwwwo.....",
		".....oggggo.....",
		"......oooo......",
		".....s....s.....",
		"....s......s....",
		"...g........g...",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"brute": [
		"ss..............",
		"ss...soooos.....",
		"sso.soffffos....",
		"ossoohhhhhho....",
		"oossohheeho.....",
		".oosohhhhhho....",
		"..oswwggwwso....",
		"..oswfffffwso...",
		"..oswflfllwso...",
		"..oswwwwwwso....",
		"...ossoosso.....",
		"...oooooooo.....",
		"..oo......oo....",
		"................",
		"................",
		"................",
	],
	"stalker": [
		"................",
		"................",
		"...ssooooooss...",
		"...sfhhhhhfs....",
		"...sfheeefs.....",
		"...sffffffs.....",
		"gggggggggggggggg",
		"...s.ssss.s.....",
		"...s..ss..s.....",
		"..ss......ss....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"bomber": [
		"................",
		"..........g.....",
		".........g......",
		"........o.......",
		"......ooooo.....",
		".....ohhhhho....",
		"....ohffffho....",
		"....ohfeeefho...",
		"....ohffffho....",
		".....oooooo.....",
		"......s..s......",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"hexer": [
		"......gggg......",
		".....gllllg.....",
		"......oooo......",
		".....offffo.....",
		"....offeeffo....",
		"....offffffo....",
		"...offssssffo...",
		"..offfllllffo...",
		".g.offfffffo.g..",
		"glg.offfffo.glg.",
		".g..offfffo..g..",
		"....oooooooo....",
		".....s....s.....",
		"................",
		"................",
		"................",
	],
	"sentinel": [
		"................",
		"....ssssssss....",
		"...sfffffffs....",
		"..sfggggggffs...",
		"..sfffffffffs...",
		".sffeeffeefffs..",
		".sfffffffffffs..",
		".sfssffffssffs..",
		".sfffffffffffs..",
		"..sfffffffffs...",
		"..ssoooooosss...",
		"...s.s..s.s.....",
		"...s..s..s......",
		"................",
		"................",
		"................",
	],
	"splitter": [
		"................",
		"....sss..sss....",
		"...sffssfffs....",
		"..sfhfsfhfhfs...",
		"..sfeessfeefs...",
		"..sfhfsfhfhfs...",
		"...sffssfffs....",
		"....sss..sss....",
		".....g....g.....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"charger": [
		"................",
		"..ss........ss..",
		"..sgs......sgs..",
		"..sggssoossggs..",
		"...sffffffffs...",
		"..sffeeffeeffs..",
		".sffffffffffffs.",
		".sffhhhhhhhhffs.",
		".sffffffffffffs.",
		"..sfffffffffffs.",
		"...ssssssssss...",
		"...s.s....s.s...",
		"..ss.s....s.ss..",
		"................",
		"................",
		"................",
	],
	"summoner": [
		"......gggg......",
		".....gllllg.....",
		"......oooo......",
		".....owwwwo.....",
		"....owheeewo....",
		"....owwwwwwo....",
		"...sffffffffs...",
		"..sflhhhhhlfs...",
		".g.sfffffffs.g..",
		"glg.sfffffs.glg.",
		".g..sfffffs..g..",
		"....ssssssss....",
		".....s....s.....",
		"................",
		"................",
		"................",
	],
	"lurker": [
		"................",
		"................",
		"................",
		"......ssss......",
		"....ssffffss....",
		"...sfheehefs....",
		"..sffffffffffo..",
		".sfgggggggggfs..",
		".sffffffffffffs.",
		"..ssssssssssss..",
		"...s.s....s.s...",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"ravager": [
		"..s..................s..",
		"..ss.....gggggg.....ss..",
		"..sso...glleelg....oss..",
		"..osso..glllllg...osso..",
		"..oosso.glllllg..ossoo..",
		"...oosofffffffoossoo....",
		"...oosohhhhhhhosso......",
		"..oosohheeheehooso......",
		".oosohhhhhhhhhhso.......",
		".ossoffffffffffffo......",
		".osssffffggggffffo......",
		".ossoffffffffffffo......",
		".oossoffffffffffoo......",
		"..oosswwwwwwwwwsoo......",
		"...osww......wwso.......",
		"...osw........wso.......",
		"...osso......osso.......",
		"...oooo......oooo.......",
		"..oo............oo......",
		".oo..............oo.....",
		"........................",
		"........................",
		"........................",
		"........................",
	],
	"stormcaller": [
		"g......................g",
		".g.....oooooooo.....g...",
		"g.....ohhhhhhho......g..",
		".....ohlleeellho........",
		".....ohlllllllho........",
		"......offfffffo.........",
		".....offggggffo.........",
		"....offfffffffo.........",
		".....owwwwwwwwo.........",
		"......owwwwwwo..........",
		".......o....o...........",
		"......s......s..........",
		".....g........g.........",
		"....g..........g........",
		"...g............g.......",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
	],
}

const ICE_ROWS := {
	"grunt": [
		"................",
		".....llllll.....",
		"....lwwwwwl.....",
		"...lwffffffl....",
		"..lwfeeewwfl....",
		"..lwfffffffl....",
		"...lwwmmmwwl....",
		"....lllllll.....",
		".....sffffs.....",
		"....sffffffs....",
		".....s.ss.s.....",
		"....s......s....",
		"................",
		"................",
		"................",
		"................",
	],
	"swarmling": [
		".g...g....g...g.",
		"..g.llllllll.g..",
		".gl.lwwwwwl.lg..",
		"..l.lwfeeewl.l..",
		".gl.lwwwwwl.lg..",
		"..l.lwlllw.l.l..",
		".g.l.lwwwl.l.g..",
		"g.l...llll...l.g",
		".g.l.l....l.l.g.",
		"..g.l......l.g..",
		".g.g........g.g.",
		"..g..........g..",
		"................",
		"................",
		"................",
		"................",
	],
	"spitter": [
		"................",
		"....sss.........",
		"...sfffsssss....",
		"..sffeeffffs....",
		"..sffffffffs.g..",
		"...ssssssss.gg..",
		"....s....s.g....",
		"...s......s.....",
		"..ss......ss....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"drifter": [
		"..g..........g..",
		".glg...oo...glg.",
		"glllg.owwo.glllg",
		".glg.oweewo.glg.",
		"..g..owwwwo..g..",
		"......oooo......",
		"......s..s......",
		".....s....s.....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"brute": [
		"................",
		"...ss......ss...",
		"..sffs....sffs..",
		"..sfffsoosfffs..",
		"...sffffffffs...",
		"..sffeeffeeffs..",
		".sffffffffffffs.",
		".sffmmmmmmmmffs.",
		".sffffffffffffs.",
		"..sfffffffffffs.",
		"...ssssssssss...",
		"...s.s....s.s...",
		"..ss......ss....",
		"................",
		"................",
		"................",
	],
	"stalker": [
		"................",
		"................",
		"ssssssssssssssss",
		"..sfggggggggfs..",
		"...sfeeeeefs....",
		"....sfffffs.....",
		".....sssss......",
		"......s..s......",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"bomber": [
		"................",
		"................",
		"......gggg......",
		".....gllllg.....",
		"....glwwwlwlg...",
		"....glwlwlwlg...",
		".....gllllg.....",
		"......gggg......",
		".......ss.......",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"hexer": [
		"......gggg......",
		".....gllllg.....",
		"......oooo......",
		".....owwwwo.....",
		"....owgeeewo....",
		"....owwwwwwo....",
		"...sffffffffs...",
		"..sflhhhhhlfs.g.",
		".w.sfffffffs.gl.",
		"wlw.sfffffs.gll.",
		".w..sfffffs..g..",
		"....ssssssss....",
		".....s....s.....",
		"................",
		"................",
		"................",
	],
	"sentinel": [
		"................",
		"......gggg......",
		".....gllllg.....",
		"....glwwwlwlg...",
		"....sfffffffs...",
		"...sffeeffeeffs.",
		"...sfffffffffffs",
		"...sssssssssss..",
		"....s.s..s.s....",
		"....s..ss..s....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"splitter": [
		"................",
		"....ggg..ggg....",
		"...gllg.gllg....",
		"..glwlgglwlg....",
		"...gllg.gllg....",
		"....ggg..ggg....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"charger": [
		"................",
		"..gg........gg..",
		"..glg......glg..",
		"..gllgsoosgllg..",
		"...sffffffffs...",
		"..sffeeffeeffs..",
		".sffffffffffffs.",
		".sfffffffffffs..",
		"..sffffffffffs..",
		"...ssssssssss...",
		"...s.s....s.s...",
		"..ss.s....s.ss..",
		"................",
		"................",
		"................",
		"................",
	],
	"summoner": [
		"......oooo......",
		".....owwwwo.....",
		"....owmmmwo.....",
		"....owheeewo....",
		"....owwwwwwo....",
		"...sffffffffs...",
		"..sfgggggggfs...",
		".g.sfffffffs.g..",
		"glg.sfffffs.glg.",
		".g..sssssss..g..",
		".....s....s.....",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"lurker": [
		"................",
		"................",
		"................",
		".....lllllll....",
		"....lwwwwwwl....",
		"...lwfeeewwl....",
		"..lwwwwwwwwwl...",
		"...lllllllll....",
		"....s.....s.....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"ravager": [
		"..s..................s..",
		"..ss....llllllll....ss..",
		"..sso..lwwwwwwwwl..oss..",
		"..osso.lwfeeewwwl.osso..",
		"..oosso.lwwwwwwwl.osso..",
		"...oossllllllllssoo.....",
		"...oossffffffffsso......",
		"..oossffffffffffso......",
		".oossffffffffffffo......",
		".ossoffffffffffffo......",
		".osssffffggggffffo......",
		".ossoffffffffffffo......",
		".oossoffffffffffoo......",
		"..oosswwwwwwwwwsoo......",
		"...osww......wwso.......",
		"...osw........wso.......",
		"...osso......osso.......",
		"...oooo......oooo.......",
		"..oo............oo......",
		".oo..............oo.....",
		"........................",
		"........................",
		"........................",
		"........................",
	],
	"stormcaller": [
		"g......................g",
		".g....llllllllll....g...",
		"g....lwwwwwwwwwwl....g..",
		"....lwggeeegggwwl.......",
		"....lwwwwwwwwwwwl.......",
		".....lffffffffffl.......",
		"....lfffffffffffl.......",
		".....lwwwwwwwwwl........",
		"......lwwwwwwwl.........",
		".......l....l...........",
		"......g......g..........",
		".....g........g.........",
		"....g..........g........",
		"...g............g.......",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
	],
}

const DOCKS_ROWS := {
	"grunt": [
		"................",
		"................",
		"...o........o...",
		"..oso......oso..",
		"...oooooooooo...",
		"...offfffffo....",
		"..offeeffeeffo..",
		"..offfffffffo...",
		"...oowwwwwwoo...",
		"....oooooooo....",
		"...o.o....o.o...",
		"..oo.o....o.oo..",
		"................",
		"................",
		"................",
		"................",
	],
	"swarmling": [
		".n...n....n...n.",
		"..n.oooooooo.n..",
		".no.offfffo.on..",
		"..o.ofheeefo.o..",
		".no.offfffo.on..",
		"..o.offlllfo.o..",
		".n.o.offfo.o.n..",
		"n.o...oooo...o.n",
		".n.o.o....o.o.n.",
		"..n.o......o.n..",
		".n.n........n.n.",
		"..n..........n..",
		"................",
		"................",
		"................",
		"................",
	],
	"spitter": [
		".......mm.......",
		"......mllm......",
		".....mlhhlm.....",
		"......mmmm......",
		"......oooo......",
		".....osssso.....",
		"....oseeesso....",
		"...osssssso.n...",
		"...ooooooo.nn...",
		"....o....o.n....",
		"...oo....oo.....",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"drifter": [
		"ww............ww",
		".w....oooo....w.",
		"w....owwwwo....w",
		"....oweeeewo....",
		"....owwwwwwo....",
		".....onnnno.....",
		"......oooo......",
		".....n....n.....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"brute": [
		"ss..............",
		"ss...soooos.....",
		"sso.smmmmmms....",
		"ossosmmmmmmso...",
		"oossomheeemso...",
		".oosommmmmmso...",
		"..oswwsswwso....",
		"..oswssssswso...",
		"..oswslslswso...",
		"..oswwwwwwso....",
		"...ossoosso.....",
		"...oooooooo.....",
		"..oo......oo....",
		"................",
		"................",
		"................",
	],
	"stalker": [
		"................",
		"................",
		"nnnnnnnnnnnnnnnn",
		"..nfggggggggfn..",
		"...nfeeeeefn....",
		"....nfffffn.....",
		".....nnnnn......",
		"......n..n......",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"bomber": [
		"................",
		"................",
		".....oooooo.....",
		"....ohhhhhho....",
		"....osssssso....",
		"....ohghhgho....",
		"....osssssso....",
		".....oooooo.....",
		"......h..h......",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"hexer": [
		"......nnnn......",
		".....nlllln.....",
		"......oooo......",
		".....osssso.....",
		"....oseeesso....",
		"....osssssso....",
		"...offfffffo....",
		"..offllllffo.n..",
		".g.offffffo.nn..",
		"glg.offffo.nln..",
		".g..offffo..n...",
		"....oooooooo....",
		".....o....o.....",
		"................",
		"................",
		"................",
	],
	"sentinel": [
		"................",
		"....mmmmmmmm....",
		"...mlllllllm....",
		"..mhhmmmmhhmm...",
		"..mmmmmmmmmmm...",
		".mmfeeffeeffmm..",
		".mmmmmmmmmmmm...",
		".mmssmmmmssmm...",
		"..mmmmmmmmmmm...",
		"...moooooomm....",
		"...m.m..m.m.....",
		"...m..m..m......",
		"................",
		"................",
		"................",
		"................",
	],
	"splitter": [
		"................",
		".....oooooo.....",
		"....osssssso....",
		"...osffooffso...",
		"..osfffoofffso..",
		"..oseefooeefso..",
		"..osfffoofffso..",
		"...osssssssso...",
		"....oooooooo....",
		".....n....n.....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"charger": [
		"................",
		"nn..............",
		"nnn...oooo......",
		".nnn.osssso.....",
		"..nnosffffso....",
		"...osfeeffso....",
		"...osffffso.....",
		"...osssssso.....",
		"....oooooo......",
		"....o.o..o......",
		"...oo.o..oo.....",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"summoner": [
		"......hhhh......",
		".....hllllh.....",
		"......oooo......",
		".....osssso.....",
		"....oseeesso....",
		"....osssssso....",
		"...offfffffo....",
		"..offllllffo....",
		".h.offffffo.h...",
		"hlh.offffo.hlh..",
		".h..offffo..h...",
		"....oooooooo....",
		".....o....o.....",
		"................",
		"................",
		"................",
	],
	"lurker": [
		"................",
		"................",
		"................",
		".....oooooo.....",
		"....osssssso....",
		"...osheeheso....",
		"..osssssssso....",
		".osllllllllso...",
		"..oooooooooo....",
		"...o.o....o.....",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"ravager": [
		"..n..................n..",
		"..nn....oooooooo....nn..",
		"..nno..osssssssso..onn..",
		"..onno.oseeeessso.onno..",
		"..oonno.osssssso.oonno..",
		"...oonosffffffsonoo.....",
		"...oonosffffffsono......",
		"..oonosffffffffsno......",
		".oonosffffffffffno......",
		".onnosffffffffffno......",
		".onnnsfffhhhhfffno......",
		".onnosffffffffffno......",
		".oonnosffffffffnno......",
		"..oonnwwwwwwwwwnno......",
		"...onww......wwno.......",
		"...onw........wno.......",
		"...onno......onno.......",
		"...oooo......oooo.......",
		"..oo............oo......",
		".oo..............oo.....",
		"........................",
		"........................",
		"........................",
		"........................",
	],
	"stormcaller": [
		"w......................w",
		".w....nnnnnnnnnn....w...",
		"w....nllllllllnn.....w..",
		"....nlweeewwwwln........",
		"....nlllllllllln........",
		".....nffffffffn.........",
		"....nffffffffffn........",
		".....nwwwwwwwwwn........",
		"......nwwwwwwwwn........",
		".......n....n...........",
		"......n......n..........",
		".....w........w.........",
		"....w..........w........",
		"...w............w.......",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
	],
}


static func all_sprites() -> Dictionary:
	var sprites: Dictionary = {}
	_pack(sprites, "volcano", VOLCANO_ROWS, VOLCANO)
	_pack(sprites, "ice", ICE_ROWS, ICE)
	_pack(sprites, "docks", DOCKS_ROWS, DOCKS)
	var world := preload("res://tools/tobor_world_art.gd")
	for sprite_name in world.ENEMY_ROWS:
		sprites["factory_%s" % sprite_name] = {
			"rows": world.ENEMY_ROWS[sprite_name],
			"palette": world.ENEMY_PALETTES[sprite_name],
		}
	for sprite_name in world.BOSS_ROWS:
		sprites["factory_%s" % sprite_name] = {
			"rows": world.BOSS_ROWS[sprite_name],
			"palette": world.BOSS_PALETTES[sprite_name],
		}
	return sprites


static func _pack(sprites: Dictionary, biome: String, rows_by_name: Dictionary, palette: Dictionary) -> void:
	for sprite_name in rows_by_name:
		sprites["%s_%s" % [biome, sprite_name]] = {
			"rows": rows_by_name[sprite_name],
			"palette": palette,
		}
