class_name ToborWorldArt
extends RefCounted

## SuperMercator robots and biome tiles. SpriteArt prefixes every id with tw_.

## Global terrain tone knob. The biome tiles shipped saturated (electric oranges,
## teal, pure blues); the player asked for the old, muted grass-meadow feel. TERRAIN_SAT_
## ADJUST scales every tile/void/decal/rock palette's saturation toward gray before the
## sprites are registered, so a single constant retunes the whole world without hand-
## editing each palette. 1.0 = original, 0.0 = grayscale. Grass meadow tiles are
## authored separately and skip this. 0.48 mutes volcano/ice/factory/docks ground.
const TERRAIN_SAT_ADJUST := 0.48
## Matching luminance lift so muting doesn't read as darkening the world. 0 = keep.
const TERRAIN_LIGHT_ADJUST := 0.08

const ENEMY_PALETTES := {
	"grunt": {"o": "1a1210", "f": "8b95a1", "l": "dfe6f2", "e": "181410", "w": "3a4656", "g": "e85a2a"},
	"swarmling": {"o": "1a1210", "f": "e85a2a", "l": "ffe08c", "e": "181410", "w": "dfe6f2"},
	"spitter": {"o": "1a1210", "f": "3a4656", "l": "7fd4ff", "e": "e82e26", "w": "dfe6f2", "g": "4f8fe0"},
	"drifter": {"o": "1a1210", "f": "8b95a1", "l": "dfe6f2", "e": "181410", "w": "f2f4f0", "g": "4f8fe0"},
	"brute": {"o": "1a1210", "f": "c43018", "l": "ffe08c", "e": "181410", "w": "5a6270", "s": "3a4656", "h": "dfe6f2"},
	"stalker": {"o": "1a1210", "f": "e85a2a", "l": "f2f4f0", "e": "181410", "w": "4f8fe0"},
	"bomber": {"o": "1a1210", "f": "e82e26", "l": "ffe14a", "e": "181410", "w": "f2f4f0"},
	"hexer": {"o": "1a1210", "f": "3a4656", "l": "50f59e", "e": "181410", "w": "dfe6f2", "g": "7fd4ff"},
	"sentinel": {"o": "1a1210", "f": "5a6270", "l": "dfe6f2", "e": "e82e26", "w": "8b95a1", "g": "ffe14a"},
	"splitter": {"o": "1a1210", "f": "4f8fe0", "l": "d8ecff", "e": "181410", "w": "f2f4f0", "g": "50f59e"},
	"charger": {"o": "1a1210", "f": "e85a2a", "l": "f2f4f0", "e": "181410", "w": "4f8fe0", "g": "e82e26"},
	"summoner": {"o": "1a1210", "f": "c43018", "l": "f2f4f0", "e": "181410", "w": "6d7680", "g": "ffe14a"},
	"lurker": {"o": "2a2010", "f": "c9a227", "l": "ffe08c", "e": "181410", "w": "f2f4f0"},
}

const ENEMY_ROWS := {
	"grunt": [
		"................",
		"..oooooooooooo..",
		"..ol.l.l.l.llo..",
		"..ol.l.l.l.llo..",
		"..olgggggggglo..",
		"..ollllllllllo..",
		"..oooooooooooo..",
		"..ow........wo..",
		"..owwwwwwwwwwo..",
		"...o.o....o.o...",
		"...oo......oo...",
		"..oo........oo..",
		"................",
		"................",
		"................",
		"................",
	],
	"swarmling": [
		".w...w....w...w.",
		"..w.oooooooo.w..",
		".wo.offffffo.ow.",
		"..o.ofleeelfo.o.",
		".wo.offffffo.ow.",
		"..o.offllllfo.o.",
		".w.o.offffo.o.w.",
		"w.o...oooo...o.w",
		".w.o.o....o.o.w.",
		"..w.o......o.w..",
		".w.w........w.w.",
		"..w..........w..",
		"................",
		"................",
		"................",
		"................",
	],
	"spitter": [
		".......gg.......",
		"......gllg......",
		".....gllelg.....",
		".....gllllg.....",
		"......oooo......",
		".....offffo.....",
		"....offffffo..o.",
		"...owwwwwwwoofo.",
		"...ow......wooo.",
		"...oo......oo...",
		"..oo........oo..",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"drifter": [
		"ww............ww",
		".w....oooo....w.",
		"w....offffo....w",
		"....ofleeelfo...",
		"....offffffo....",
		".....oggggo.....",
		"......oooo......",
		".....o....o.....",
		"....o......o....",
		"...o........o...",
		"................",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"brute": [
		"ss..............",
		"ss....oooo......",
		"sso..ohhhho.....",
		"ossoohhhhhho....",
		"oossohhhhhho....",
		".oosohhhhhho....",
		"..oswwwwwwwo....",
		"..oswfffffwso...",
		"..oswfeefwso....",
		"..oswwwwwwso....",
		"...ossoosso.....",
		"...oooooooo.....",
		"..oo......oo....",
		"................",
		"................",
		"................",
	],
	"stalker": [
		"................",
		"................",
		"...oooooooooo...",
		"...ofllllllfo...",
		"...ofleeeelfo...",
		"...offfffffo....",
		"wwwwwwwwwwwwwwww",
		"w..............w",
		".wwwwwwwwwwwwww.",
		"..o.o......o.o..",
		"...oo......oo...",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"bomber": [
		"................",
		".........ll.....",
		"........l.l.....",
		".......l........",
		".....oooooo.....",
		"....offffffo....",
		"...offwweewfo...",
		"...offwwwwffo...",
		"...offfffffo....",
		"....ooooooo.....",
		".....o...o......",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"hexer": [
		".......gg.......",
		"......gllg......",
		".....gllllg.....",
		"....oooooooo....",
		"...owwwwwwwwo...",
		"...owlgggglwo...",
		"...owllllllwo...",
		"...owleeeelwo...",
		"...owfffffo.....",
		"....owwwwwwo....",
		"....oo....oo....",
		"...oo......oo...",
		"................",
		"................",
		"................",
		"................",
	],
	"sentinel": [
		"......gggg......",
		".....gwwwg......",
		"....gwleewg.....",
		"....gwwwwwg.....",
		".....oooo.......",
		"......oo........",
		".....offfo......",
		"....offffffo....",
		"...ow......wo...",
		"...oo......oo...",
		"..oo........oo..",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"splitter": [
		"................",
		"....oooooooo....",
		"...oggggggggo...",
		"...ollllllllo...",
		"...olffeefflo...",
		"...ollllllllo...",
		"....oooooooo....",
		"....ollllllo....",
		"...olfffffflo...",
		"...olfffffflo...",
		"....oooooooo....",
		".....o....o.....",
		"....oo....oo....",
		"................",
		"................",
		"................",
	],
	"charger": [
		"......gggg......",
		".....gllllg.....",
		"....glleelg.....",
		"....glllllg.....",
		"...offfffffo....",
		"..offffffffffo..",
		"wwwwwwwwwwwwwwww",
		"woooooooooooooow",
		".wwwwwwwwwwwwww.",
		"..o.o......o.o..",
		"...oo......oo...",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"summoner": [
		"......gggg......",
		".....gllllg.....",
		"....glleelg.....",
		"...gglllllgg....",
		"...goffffog.....",
		"..ogooooooogo...",
		"..ogffffffgo....",
		"...owwwwwwo.....",
		".o..owwwwo..o...",
		"olo.owwwwo.olo..",
		".o..oo..oo..o...",
		"....oo..oo......",
		"...oo....oo.....",
		"................",
		"................",
		"................",
	],
	"lurker": [
		"................",
		"...oooooooooo...",
		"...offffffffo...",
		"...ofllllllfo...",
		"...ofleeeelfo...",
		"...ofllllllfo...",
		"...offffffffo...",
		"...offffffffo...",
		"...offffffffo...",
		"...oooooooooo...",
		"....o......o....",
		"...oo......oo...",
		"................",
		"................",
		"................",
		"................",
	],
}

const BOSS_PALETTES := {
	"ravager": {"o": "1a0808", "f": "c43018", "l": "f2f4f0", "e": "181410", "w": "5a6270", "g": "e82e26", "s": "3a4656"},
	"stormcaller": {"o": "101418", "f": "8b95a1", "l": "f2f4f0", "e": "181410", "w": "dfe6f2", "g": "e82e26", "y": "ffe14a"},
}

const BOSS_ROWS := {
	"ravager": [
		"ss......gggg......ss....",
		"sso....gllllg....oss....",
		"osso..glleelg...osso....",
		"oosso.glllllg..ossoo....",
		".oosofffffffoossoo......",
		".oosoffffffffosso.......",
		"oosfffffffffffooso......",
		"oosffffffffffffffso.....",
		"ossffffffffffffffss.....",
		"osssffffffffffffssso....",
		"ossoffffffffffffosso....",
		"oossoffffffffffossoo....",
		".oosswwwwwwwwwssoo......",
		"..oswwwwwwwwwwso........",
		"..osww......wwso........",
		"..oswgg....ggwso........",
		"..ossog....gosso........",
		"..oooo......oooo........",
		".oo............oo.......",
		"oo..............oo......",
		"o................o......",
		"........................",
		"........................",
		"........................",
	],
	"stormcaller": [
		"ww......oooooo......ww..",
		".w.....oyyyyyyo......w..",
		"w.....oylleellyo......w.",
		".....oylllllllyo........",
		"......offffffffo........",
		".....offggggfffo........",
		"......owwwwwwwwo........",
		".....oowwwwwwwoo........",
		"....o..owwwwwwo..o......",
		"...o....o....o....o.....",
		"..ww...o......o...ww....",
		".w....o........o....w...",
		"w....ww........ww....w..",
		"....w............w......",
		"...w..............w.....",
		"..w................w....",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
	],
}

const PROP_PALETTES := {
	"spit": {"o": "07203d", "f": "4f8fe0", "l": "d8ecff"},
	"bolt": {"o": "3a2008", "f": "ff7a29", "l": "ffe08c"},
	"spark": {"o": "6b1408", "f": "e82e26", "l": "ffe14a"},
	"xp_orb": {"o": "6b2f05", "f": "e85a2a", "l": "ffe08c"},
	"coin": {"o": "6b4a05", "f": "ffc93c", "l": "fff0b8"},
}

const PROP_ROWS := {
	"spit": [
		"...ff...",
		"..fllf..",
		".ffllff.",
		"ffffffff",
		".ffooff.",
		"..oooo..",
		"........",
		"........",
	],
	"bolt": [
		"f......f",
		".f.ff.f.",
		"..fllf..",
		".ffllff.",
		"..fllf..",
		".f.ff.f.",
		"f......f",
		"........",
	],
	"spark": [
		"...l....",
		"..flf...",
		".fflff..",
		"lfffffl.",
		".fflff..",
		"..flf...",
		"...o....",
		"........",
	],
	"xp_orb": [
		"........",
		"..oooo..",
		".offffo.",
		"offllffo",
		"offllffo",
		".offffo.",
		"..oooo..",
		"........",
	],
	"coin": [
		"..oooo..",
		".offffo.",
		"offllffo",
		"ofllllfo",
		"ofllllfo",
		"offllffo",
		".offffo.",
		"..oooo..",
	],
}

const _TILE := [
	"bcbbabbcbbabbcbb",
	"bbbccbbbbcbbbbab",
	"abbbbbabcbbbdbbb",
	"bbcbbbbbbbbabbcb",
	"bbbabdbbcbbbbbbb",
	"cbbbbbbbabbbcbba",
	"bbbcbabbbbcbbbbb",
	"abbbbbcbbbabbcbb",
	"bbcbbbbbbbdbbbba",
	"bbbbabbcbbbbabbb",
	"cbbbdbbbbabbbcbb",
	"bbabbbbcbbbbbbba",
	"bbbbcbabbbcbbcbb",
	"abbbbbbbbbbabbbb",
	"bbcbbabdbbbbcbba",
	"bbbbbbbbabbbbbbb",
]
const _FACTORY_TILE := [
	"abababababababab",
	"babcbabababababa",
	"abababababcbabab",
	"babababababababa",
	"ababcbababababab",
	"babababababcbaba",
	"abababababababab",
	"babababcbabababa",
	"abababababababab",
	"babcbabababababa",
	"abababababcbabab",
	"babababababababa",
	"ababcbababababab",
	"babababababcbaba",
	"abababababababab",
	"babababababababa",
]
const _DOCKS_TILE := [
	"bbbbbbbbbbbbbbbb",
	"acacacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacacacaca",
	"bbbbbbbbbbbbbbbb",
	"acacacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacacacaca",
	"bbbbbbbbbbbbbbbb",
	"acacacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacacacaca",
	"bbbbbbbbbbbbbbbb",
	"acacacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacacacaca",
]

const TERRAIN_PALETTES := {
	"grass_tile": {"a": "5c5044", "b": "6e5e4e", "c": "4a4038", "d": "e08a3a"},
	"grass_tuft": {"c": "3a3028", "d": "2a2018", "l": "c45a20"},
	"grass_flower": {"c": "6e5e4e", "d": "e8e4d8", "p": "f6f1e4", "w": "ffffff"},
	"grass_bloom": {"c": "6e5e4e", "d": "c43018", "y": "e85a2a", "w": "ffe08c"},
	"rock_small": {"o": "1a1210", "s": "6b4a1a", "m": "c9a227", "h": "ffe08c", "g": "3a2a10"},
	"rock_large": {"o": "121418", "s": "3a4656", "m": "5a6270", "h": "8b95a1", "g": "2bbfbe"},
	"boulder": {"o": "121418", "s": "3a2a10", "m": "6b4a1a", "h": "c9a227", "g": "2a2010"},
	"spire": {"o": "101418", "s": "3a4656", "m": "5a6270", "h": "8b95a1", "w": "ffe14a"},
	"shop_stand": {
		"o": "1a1210", "f": "e8d4a8", "t": "c43018", "l": "ffa090",
		"k": "181410", "s": "8b95a1", "m": "5a6270", "w": "e8e8e8",
		"e": "ff9a28", "y": "ffe08c", "a": "fff6c8", "r": "e85a2a",
		"c": "6b4a2c", "b": "3a2418", "u": "d0d0d0", "h": "f4f4f4",
		"i": "f2b090", "q": "6d7680", "d": "2a3038", "p": "4f8fe0",
	},
}

const TERRAIN_ROWS := {
	"grass_tile": _TILE,
	"grass_tuft": [
		"........",
		"........",
		"...l....",
		"..ldl...",
		".ldcdl..",
		"..dcd...",
		"...c....",
		"........",
	],
	"grass_flower": [
		"........",
		"........",
		".pppppp.",
		".pwwwwp.",
		".pppppp.",
		"........",
		"........",
		"........",
	],
	"grass_bloom": [
		"........",
		"...y....",
		"..ywy...",
		"...y....",
		"...d....",
		"..dcd...",
		"...c....",
		"........",
	],
	"rock_small": [
		"................",
		"................",
		"....oooooooo....",
		"...ohhhhhhho....",
		"...ommmmmmmo....",
		"...ohhhhhhho....",
		"...ommmmmmmo....",
		"...ogsssssgo....",
		"....oooooooo....",
		"....o....o......",
		"....o....o......",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"rock_large": [
		"................",
		"...oooooooooo...",
		"..ohhhhhhhhho...",
		"..ommmmmmmmmo...",
		"..ohhhggghhho...",
		"..ommmmmmmmmo...",
		"..ossssssssso...",
		"..ossssssssso...",
		"...oooooooooo...",
		"...o........o...",
		"...o........o...",
		"................",
		"................",
		"................",
		"................",
		"................",
	],
	"shop_stand": [
		"......................tlt.......................",
		"..............ooooooootttoooooooo...............",
		"..............offfffffffffffffffo...............",
		"..............ofttttttffsffsffffo...............",
		"..............oftkttktfffsmfffffo......ttttttt..",
		"..............ofttktttfffssfffffo......ttttttt..",
		"..............ofttttttffsffsffffo......tttwttt..",
		"..............ooooooooooooooooooo......ttwtwtt..",
		".....s.ooooooooooooooooooooooooooooooo.tttwttt..",
		"....eeeorrrrrrrrrrrrrrrrrrrrrrrrrrrrro.ttttttt..",
		"....eyeortttttttttttttttttttttttttttro...s......",
		"....eaeorrrrrrrrrrrrrrrrrrrrrrrrrrrrro...s......",
		"....eeeortttttttttttttttttttttttttttro...s......",
		".......orrrrrrrrrrrrrrrrrrrrrrrrrrrrro...sm.....",
		".......ooooooooooooooooooooooooooooooo...mmmmmm.",
		".........ooooooooooooooooooooooooooo.....mmmmmm.",
		".........occccccccccccccccccccccccco.....mmmmmm.",
		".........occmcccccccccccccccccccccco.....s.mmmm.",
		".........ocbsssssboottlttysbbbsbbbco.....s.mmmm.",
		".........ocbmbbbbboptttttsbbbtttbbco.......mmmm.",
		".........ocbbbbbbbouuuuuuubbbsltbbco.oooooommmm.",
		".........ocbbbbbbbouhhhhhsssusttbbco.oqqqqqmmmm.",
		".........ocbbbbbbbouhkhkhsssssttbbco.oqqqqqqqqo.",
		".........ocbbbbbbbouhhihhubbbtttbbco.oqqqqqqqqo.",
		".........ocbbbbbbbbuuuuuuubbbbbbbbco.oqqqqqqqqo.",
		".........ocbbbbbbbbbsssssbbbbbbbbbco.oqkkkkkkqo.",
		".ooooooo.ocbbbbbbbbbsssssbbbbbbbbbco.oqkkkkkkqo.",
		".occccco.occccccccccssssscccccccccco.oqkeeeekqo.",
		".octttcoooooooooorrrrrrrrrrrooooooooooqkeeaekqo.",
		".octttcoocccccccctttttttttttccccccccooqkeyeekqo.",
		".octftcoocbbbbbbbtttttttttttbbbbbbbcooqkeeeekqo.",
		".octttcoocbbbbbbbtttttttttttbbbbbbbcooqkeeeekqo.",
		".octttcoocbbbbbbbtttttttttttbbbbbbbcooqkeeeekqo.",
		".occcccoocdddddbdddddbdddddbddsddbbcooqkkkkkkqo.",
		".occcccoocdsdsdbdspsdbdtdtdbdtttdbbcooqqqqqqqqo.",
		".occcccoocddsddbdsssdbddtddbdtttdbbcooqqqqqqqqo.",
		".occcccoocdddddcdddddcdddddcdddddcccooqqqqqqqqo.",
		".oooooooooooooooooooooooooooooooooooooooooooooo.",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
	],
	"boulder": [
		"........................",
		"......oooooooooo........",
		".....ohhhhhhhhho........",
		".....ommmmmmmmmo........",
		"...ooohhhhhhhhhoooo.....",
		"..ohhhmmmmmmmmmmhhho....",
		"..ommmhhhhhhhhhhmmmo....",
		"..ohhhmmmmmmmmmmhhho....",
		"..ogggssssssssssgggo....",
		"...oooooooooooooooo.....",
		"....o....o....o.........",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
		"........................",
	],
	"spire": [
		"........................",
		"..........ow............",
		".........omwo...........",
		".........omwo...........",
		"........osmwo...........",
		"........osmwo...........",
		"........osmwo...........",
		".......oosmwo...........",
		".......osmmwo...........",
		".......osmmwo...........",
		".......osmmwo...........",
		"......oosmmwo...........",
		"......osmmmwo...........",
		"......osmmmwo...........",
		"......osmmmwo...........",
		"......ssmmmwo...........",
		"......sssssso...........",
		"......ooooooo...........",
		".......o...o............",
		".......o...o............",
		"........................",
		"........................",
		"........................",
		"........................",
	],
}

## Extra biome tiles/obstacles. Sprite ids become tw_volcano_grass_tile, etc.
## Each world has its own ground language: lava-cracked basalt, packed snow,
## riveted plates, and plank boardwalks — not recolored meadow noise.
const BIOME_TILE_PALETTES := {
	"volcano": {"a": "2a1612", "b": "3d2218", "c": "1a0c08", "d": "e85a2a", "e": "ff7a29"},
	"ice": {"a": "c8dcec", "b": "e4f2fa", "c": "8ab0c8", "d": "ffffff", "e": "b8d4e8"},
	"factory": {"a": "2c3038", "b": "3e4650", "c": "1a1e24", "d": "2bbfbe", "e": "e85a2a"},
	"docks": {"a": "6b4a1a", "b": "8a6230", "c": "3a2a10", "d": "2f8fb0", "e": "c9a227"},
}

const BIOME_VOID_PALETTES := {
	"volcano": {"a": "4a1408", "b": "c43018", "c": "e85a2a", "d": "ff7a29", "e": "ffe14a"},
	"ice": {"a": "0e2438", "b": "1a3a58", "c": "2a5a78", "d": "8ad7ff", "e": "d0e8f6"},
	"factory": {"a": "080a0e", "b": "12141a", "c": "1e2430", "d": "2bbfbe", "e": "e85a2a"},
	"docks": {"a": "0a2030", "b": "123848", "c": "1a5068", "d": "4f8fe0", "e": "dfe6f2"},
}

const BIOME_DECAL_PALETTES := {
	"volcano": {"c": "3a1c14", "d": "e85a2a", "l": "ff7a29", "p": "ffdc4d", "w": "fff3b0", "y": "ff7a29"},
	"ice": {"c": "9cbcd4", "d": "d0e8f6", "l": "ffffff", "p": "e8f6ff", "w": "ffffff", "y": "b8d4e8"},
	"factory": {"c": "4a4a52", "d": "2bbfbe", "l": "e85a2a", "p": "8b95a1", "w": "dfe6f2", "y": "ffe14a"},
	"docks": {"c": "8a6230", "d": "2f8fb0", "l": "c9a227", "p": "dfe6f2", "w": "ffffff", "y": "4f8fe0"},
}

const BIOME_ROCK_PALETTES := {
	"volcano": {"o": "1a0808", "s": "3a1410", "m": "c43018", "h": "e85a2a", "g": "ff7a29", "w": "ffe14a"},
	"ice": {"o": "3a5068", "s": "7aa0b8", "m": "b8d4e8", "h": "e8f6ff", "g": "ffffff", "w": "d0e8f6"},
	"factory": {"o": "101418", "s": "3a3a40", "m": "5a6270", "h": "8b95a1", "g": "2bbfbe", "w": "e85a2a"},
	"docks": {"o": "1a1210", "s": "3a2a10", "m": "6b4a1a", "h": "c9a227", "g": "2f8fb0", "w": "dfe6f2"},
}

const _VOLCANO_TILE := [
	"bbbabbbbabbbabbb",
	"baaacaaabaaacaaa",
	"bbbabdebbbabdbbb",
	"cbbabbbbbbbabbbc",
	"bbbaabbbbaaabbbb",
	"aaacaaaabaaacaaa",
	"bbbabbbdebbabbbb",
	"bbbbabbbbbbbabbb",
	"baaacaaabaaacaaa",
	"bbbabbbbbdebabbb",
	"cbbabbbbaaaabbbc",
	"bbbaabbbbbbbabbb",
	"aaacaaaabaaacaaa",
	"bbbabdebbbabbbbb",
	"bbbbabbbbbbbabbb",
	"baaacaaabaaacaaa",
]
const _ICE_TILE := [
	"bbbbdbbbbbbbdbbb",
	"bdddbbbbebbbdddb",
	"bbbbbbebbbbbbbbb",
	"bbebbbbdbbbbebbb",
	"bbbbbbbbbbbbdbbb",
	"dbbbbebbbbbbbbbd",
	"bbbbbbbbbbebbbbb",
	"bbdbbbbbbbbbdbbb",
	"bbbbbbebbbbbbbbb",
	"bebbbbbbbbbebbbb",
	"bbbbdbbbbbbbbbdb",
	"bbbbbbbbdbbbbbbb",
	"bbbebbbbbbbbbebb",
	"bbbbbbbbbbebbbbb",
	"dbbbbbbbbbbbbbbd",
	"bbbbdbbbbbbbdbbb",
]
const _FACTORY_FLOOR := [
	"cccccccccccccccc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cbbbbbeeeebbbbbc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cbbbbbeeeebbbbbc",
	"cbbbbbbbbbbbbbbc",
	"cbddddbbbbddddbc",
	"cbbbbbbbbbbbbbbc",
	"cccccccccccccccc",
]
const _DOCKS_PLANK := [
	"bbbbbbbbbbbbbbbb",
	"acacaeacacacaeac",
	"bbbbbbbbbbbbbbbb",
	"cacacacaeacacaca",
	"bbbbbbbbbbbbbbbb",
	"acaeacacacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacacacacaeacaca",
	"bbbbbbbbbbbbbbbb",
	"acacacaeacacacac",
	"bbbbbbbbbbbbbbbb",
	"cacaeacacacacaca",
	"bbbbbbbbbbbbbbbb",
	"acacacacacaeacac",
	"bbbbbbbbbbbbbbbb",
	"caeacacacacacaca",
]
const _VOLCANO_VOID := [
	"aaabaaabaaabaaab",
	"abcdeabcdeabcdea",
	"aaabaaabaaabaaab",
	"baaabaaabaaabaaa",
	"cdeabcdeabcdeabc",
	"aaabaaabaaabaaab",
	"abaaabaaabaaabaa",
	"eabcdeabcdeabcde",
	"aaabaaabaaabaaab",
	"aaabaaabaaabaaab",
	"bcdeabcdeabcdeab",
	"aaabaaabaaabaaab",
	"baaabaaabaaabaaa",
	"deabcdeabcdeabcd",
	"aaabaaabaaabaaab",
	"abaaabaaabaaabaa",
]
const _ICE_VOID := [
	"bbbbbbbbbbbbbbbb",
	"baaaaaaaeaaaaaab",
	"baaaaacaaaaaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaaeaaaaaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaadaaaaaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaaaaaaeaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaacaaaaaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaaeaaaaaaaab",
	"baaaaaaaaaaaaaab",
	"baaaaaaaadaaaaab",
	"bbbbbbbbbbbbbbbb",
]
const _FACTORY_VOID := [
	"aaaaaaaaaaaaaaaa",
	"abbbbbbbbbbbbbba",
	"abaaaaaaaaaaaaba",
	"abaaeeaaaaeeaaba",
	"abaaaaaaaaaaaaba",
	"abaaddddddddaaba",
	"abaaaaaaaaaaaaba",
	"abaaaaaaaaaaaaba",
	"abaaaaaaaaaaaaba",
	"abaaddddddddaaba",
	"abaaaaaaaaaaaaba",
	"abaaeeaaaaeeaaba",
	"abaaaaaaaaaaaaba",
	"abbbbbbbbbbbbbba",
	"aaaaaaaaaaaaaaaa",
	"aaaaaaaaaaaaaaaa",
]
const _DOCKS_VOID := [
	"bbbbbbbbbbbbbbbb",
	"bcccbcccbcccbccc",
	"bbbbbbbbbbbbbbbb",
	"cccbcccbcccbcccb",
	"bbbbbebbbbbebbbb",
	"bcccbcccbcccbccc",
	"bbbbbbbbbbbbbbbb",
	"cccbcccbcccbcccb",
	"bbbbbbbbbbbbbbbb",
	"bcccbcccdcccbccc",
	"bbbbbbbbbbbbbbbb",
	"cccbcccbcccbcccb",
	"bbbebbbbbbbbbebb",
	"bcccbcccbcccbccc",
	"bbbbbbbbbbbbbbbb",
	"cccbcccbcccbcccb",
]
const _VOLCANO_TUFT := [
	"........",
	"...y....",
	"..yly...",
	"...l....",
	"...d....",
	"..dcd...",
	"...c....",
	"........",
]
const _ICE_TUFT := [
	"........",
	"..w.w...",
	".wwwww..",
	"..www...",
	"...d....",
	"..dcd...",
	"...c....",
	"........",
]
const _FACTORY_TUFT := [
	"........",
	"...yy...",
	"...dd...",
	"..dwwd..",
	"...dd...",
	"...pp...",
	"...c....",
	"........",
]
const _DOCKS_TUFT := [
	"........",
	"........",
	"..l..l..",
	"...ll...",
	"..dddd..",
	"...dd...",
	"...c....",
	"........",
]
const _VOLCANO_ROCK := [
	"................",
	"......oooo......",
	"....oohhhhoo....",
	"...ohmmmmmmho...",
	"...ohmgwwgmho...",
	"...osmmmmmmso...",
	"....osssssso....",
	".....oooooo.....",
	".....o....o.....",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
]
const _ICE_ROCK := [
	"................",
	".......g........",
	"......ghg.......",
	".....ghhhg......",
	"....ghwmwhg.....",
	"...ghmmmmmhg....",
	"...osssssso.....",
	"....oooooo......",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
]
const _FACTORY_CRATE := [
	"................",
	"...oooooooooo...",
	"..ohhhhhhhhho...",
	"..owgggggggwo...",
	"..ohhhhhhhhho...",
	"..ommmmmmmmmo...",
	"..ohhhhhhhhho...",
	"..ossssssssso...",
	"...oooooooooo...",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
]
const _DOCKS_BARREL := [
	"................",
	".....oooooo.....",
	"....ohhhhhho....",
	"....owmmmmwo....",
	"....ohghhgho....",
	"....owmmmmwo....",
	"....osssssso....",
	".....oooooo.....",
	".....o....o.....",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
	"................",
]


static func all_sprites() -> Dictionary:
	var sprites: Dictionary = {}
	_collect(sprites, ENEMY_ROWS, ENEMY_PALETTES)
	_collect(sprites, BOSS_ROWS, BOSS_PALETTES)
	_collect(sprites, PROP_ROWS, PROP_PALETTES)
	_collect(sprites, TERRAIN_ROWS, TERRAIN_PALETTES)
	var tiles := {
		"volcano": _VOLCANO_TILE,
		"ice": _ICE_TILE,
		"factory": _FACTORY_FLOOR,
		"docks": _DOCKS_PLANK,
	}
	var voids := {
		"volcano": _VOLCANO_VOID,
		"ice": _ICE_VOID,
		"factory": _FACTORY_VOID,
		"docks": _DOCKS_VOID,
	}
	var tufts := {
		"volcano": _VOLCANO_TUFT,
		"ice": _ICE_TUFT,
		"factory": _FACTORY_TUFT,
		"docks": _DOCKS_TUFT,
	}
	var rocks := {
		"volcano": _VOLCANO_ROCK,
		"ice": _ICE_ROCK,
		"factory": _FACTORY_CRATE,
		"docks": _DOCKS_BARREL,
	}
	for biome in BIOME_TILE_PALETTES.keys():
		sprites["%s_grass_tile" % biome] = {"rows": tiles[biome], "palette": _tone_terrain(BIOME_TILE_PALETTES[biome])}
		sprites["%s_void_tile" % biome] = {"rows": voids[biome], "palette": _tone_terrain(BIOME_VOID_PALETTES[biome])}
		sprites["%s_grass_tuft" % biome] = {"rows": tufts[biome], "palette": _tone_terrain(BIOME_DECAL_PALETTES[biome])}
		sprites["%s_grass_flower" % biome] = {"rows": TERRAIN_ROWS.grass_flower, "palette": _tone_terrain(BIOME_DECAL_PALETTES[biome])}
		sprites["%s_grass_bloom" % biome] = {"rows": TERRAIN_ROWS.grass_bloom, "palette": _tone_terrain(BIOME_DECAL_PALETTES[biome])}
		sprites["%s_rock_small" % biome] = {"rows": rocks[biome], "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_rock_large" % biome] = {"rows": TERRAIN_ROWS.rock_large, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_boulder" % biome] = {"rows": TERRAIN_ROWS.boulder, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
		sprites["%s_spire" % biome] = {"rows": TERRAIN_ROWS.spire, "palette": _tone_terrain(BIOME_ROCK_PALETTES[biome])}
	return sprites


## Desaturate + lighten a biome terrain palette toward the old grass-meadow tone.
## Pure palette transform — no sprite/rows touched. TERRAIN_SAT_ADJUST is the knob.
## Public so the forge can route the untoned classic terrain through the same path.
static func tone_terrain_palette(palette: Dictionary) -> Dictionary:
	var tweaked: Dictionary = {}
	for key in palette:
		var color := Color(str(palette[key]))
		var gray := color.get_luminance()
		color.s = clampf(color.s * TERRAIN_SAT_ADJUST, 0.0, 1.0)
		color.v = clampf(lerpf(color.v, gray, TERRAIN_LIGHT_ADJUST), 0.0, 1.0)
		tweaked[key] = color.to_html(false)
	return tweaked


static func _tone_terrain(palette: Dictionary) -> Dictionary:
	return tone_terrain_palette(palette)


static func _collect(sprites: Dictionary, rows_by_name: Dictionary, palettes: Dictionary) -> void:
	for sprite_name in rows_by_name:
		sprites[sprite_name] = {
			"rows": rows_by_name[sprite_name],
			"palette": palettes[sprite_name],
		}
